Removing unused code

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -12,6 +12,7 @@ pr:
 
 jobs:
   - job: Lint_Check
+    continueOnError: true
     timeoutInMinutes: 30
     strategy:
       matrix:
@@ -22,7 +23,6 @@ jobs:
       vmImage: $(imageName)
     steps:
       - task: GoTool@0
-        continueOnError: true
         env:
           GO111MODULE: 'on'
         inputs:
@@ -35,204 +35,204 @@ jobs:
           ./bin/golangci-lint run common
         displayName: 'Golang Lint Check'
         workingDirectory: $(System.DefaultWorkingDirectory)
-
-  - job: Build
-    timeoutInMinutes: 360
-    strategy:
-      matrix:
-        Ubuntu-20:
-          imageName: 'ubuntu-20.04'
-          type: 'linux'
-        MacOS:
-          imageName: 'macOS-10.15'
-          type: 'mac-os'
-    pool:
-      vmImage: $(imageName)
-    steps:
-      - task: GoTool@0
-        inputs:
-          version: '1.16'
-      - script: |
-          GOARCH=amd64 GOOS=linux go build -o "$(Build.ArtifactStagingDirectory)/azcopy_linux_amd64"
-          GOARCH=amd64 GOOS=linux go build -tags "se_integration" -o "$(Build.ArtifactStagingDirectory)/azcopy_linux_se_amd64"
-          GOARCH=arm64 GOOS=linux go build -o "$(Build.ArtifactStagingDirectory)/azcopy_linux_arm64"
-
-          GOARCH=amd64 GOOS=windows go build -o "$(Build.ArtifactStagingDirectory)/azcopy_windows_amd64.exe"
-          GOARCH=386 GOOS=windows go build -o "$(Build.ArtifactStagingDirectory)/azcopy_windows_386.exe"
-          GOARCH=arm GOARM=7 GOOS=windows go build -o "$(Build.ArtifactStagingDirectory)/azcopy_windows_v7_arm.exe"
-
-          cp NOTICE.txt $(Build.ArtifactStagingDirectory)
-        displayName: 'Generate Linux And Windows Build'
-        condition: eq(variables.type, 'linux')
-
-      - script: |
-          go build -o "$(Build.ArtifactStagingDirectory)/azcopy_darwin_amd64"
-        displayName: 'Generate MacOS Build'
-        condition: eq(variables.type, 'mac-os')
-
-      - task: PublishBuildArtifacts@1
-        displayName: 'Publish Artifacts'
-        condition: succeededOrFailed()
-
-  - job: E2E_Test
-    timeoutInMinutes: 360
-    # Creating strategies for GOOS: Windows Server 2019 /macOS X Mojave 10.15/Ubuntu 20.04
-    strategy:
-      matrix:
-        Ubuntu-20:
-          imageName: 'ubuntu-20.04'
-          type: 'linux'
-        Windows:
-          imageName: 'windows-2019'
-          type: 'windows'
-        MacOS:
-          imageName: 'macOS-10.15'
-          type: 'mac-os'
-    pool:
-      vmImage: $(imageName)
-
-    steps:
-      - task: GoTool@0
-        inputs:
-          version: '1.16'
-
-      # Running E2E Tests on Linux - AMD64
-      - script: |
-          set -e
-          GOARCH=amd64 GOOS=linux go build -o azcopy_linux_amd64
-          export AZCOPY_E2E_EXECUTABLE_PATH=$(pwd)/azcopy_linux_amd64
-          go test -timeout 20m -race -short -cover ./e2etest
-        env:
-          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
-          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
-          AZCOPY_E2E_ACCOUNT_KEY_HNS: $(AZCOPY_E2E_ACCOUNT_KEY_HNS)
-          AZCOPY_E2E_ACCOUNT_NAME_HNS: $(AZCOPY_E2E_ACCOUNT_NAME_HNS)
-          CPK_ENCRYPTION_KEY: $(CPK_ENCRYPTION_KEY)
-          CPK_ENCRYPTION_KEY_SHA256: $(CPK_ENCRYPTION_KEY_SHA256)
-        displayName: 'E2E Test Linux - AMD64'
-        condition: eq(variables.type, 'linux')
-
-      # Running E2E Tests on Windows - AMD64
-      - script: |
-          go build -o $(System.DefaultWorkingDirectory)/azcopy_windows_amd64.exe
-          go build -o $(System.DefaultWorkingDirectory)/azcopy_windows_386.exe
-          echo 'starting E2E tests on windows'
-          go test -timeout 30m -race -cover -v ./e2etest
-        env:
-          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
-          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
-          AZCOPY_E2E_ACCOUNT_KEY_HNS: $(AZCOPY_E2E_ACCOUNT_KEY_HNS)
-          AZCOPY_E2E_ACCOUNT_NAME_HNS: $(AZCOPY_E2E_ACCOUNT_NAME_HNS)
-          CPK_ENCRYPTION_KEY: $(CPK_ENCRYPTION_KEY)
-          CPK_ENCRYPTION_KEY_SHA256: $(CPK_ENCRYPTION_KEY_SHA256)
-          AZCOPY_E2E_EXECUTABLE_PATH: $(System.DefaultWorkingDirectory)/azcopy_windows_amd64.exe
-        displayName: 'E2E Test Windows - AMD64'
-        condition: eq(variables.type, 'windows')
-
-      # Running E2E Tests on Mac
-      - script: |
-          set -e
-          go build -o azcopy_darwin_amd64
-          echo 'starting E2E tests on mac-os'
-          export AZCOPY_E2E_EXECUTABLE_PATH=$(pwd)/azcopy_darwin_amd64
-          go test -timeout 30m -race -cover -v ./e2etest
-        env:
-          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
-          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
-          AZCOPY_E2E_ACCOUNT_KEY_HNS: $(AZCOPY_E2E_ACCOUNT_KEY_HNS)
-          AZCOPY_E2E_ACCOUNT_NAME_HNS: $(AZCOPY_E2E_ACCOUNT_NAME_HNS)
-          CPK_ENCRYPTION_KEY: $(CPK_ENCRYPTION_KEY)
-          CPK_ENCRYPTION_KEY_SHA256: $(CPK_ENCRYPTION_KEY_SHA256)
-        displayName: 'E2E Test MacOs'
-        condition: eq(variables.type, 'mac-os')
-
-  - job: Test_On_Ubuntu
-    variables:
-      isMutexSet: 'false'
-    # allow maximum build time, in case we have build congestion
-    timeoutInMinutes: 360
-    pool:
-      vmImage: 'ubuntu-20.04'
-    steps:
-      - task: UsePythonVersion@0
-        name: 'Set_up_Python'
-        inputs:
-          versionSpec: '3.7'
-      - task: GoTool@0
-        name: 'Set_up_Golang'
-        inputs:
-          version: '1.16'
-      - task: DownloadSecureFile@1
-        name: ciGCSServiceAccountKey
-        displayName: 'Download GCS Service Account Key'
-        inputs:
-          secureFile: 'ci-gcs-dev.json'
-      - script: |
-          pip install azure-storage-blob==12.0.0b3
-          # the recent release 1.0.0b4 has a breaking change
-          pip install azure-core==1.0.0b3
-          # acquire the mutex before running live tests to avoid conflicts
-          python ./tool_distributed_mutex.py lock "$(MUTEX_URL)"
-          # set the variable to indicate that the mutex was actually acquired
-          echo '##vso[task.setvariable variable=isMutexSet]true'
-        name: 'Acquire_the_distributed_mutex'
-      - script: |
-          # run unit test and build executable
-          # the set -e line is needed so that the unit tests failure would cause the job to fail properly
-          # "-check.v" (must be after package list) outputs timings
-          set -e
-          go test -timeout 45m -race -short -cover ./cmd ./common ./common/parallel ./ste ./azbfs ./sddl "-check.v"
-          GOARCH=amd64 GOOS=linux go build -o azcopy_linux_amd64
-        name: 'Run_unit_tests'
-        env:
-          ACCOUNT_NAME: $(ACCOUNT_NAME)
-          ACCOUNT_KEY: $(ACCOUNT_KEY)
-          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
-          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
-          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
-          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
-          GOOGLE_APPLICATION_CREDENTIALS: $(ciGCSServiceAccountKey.secureFilePath)
-          GOOGLE_CLOUD_PROJECT: $(GOOGLE_CLOUD_PROJECT)
-      - script: |
-          go build -o test-validator ./testSuite/
-          mkdir test-temp
-          export AZCOPY_EXECUTABLE_PATH=$(pwd)/azcopy_linux_amd64
-          export TEST_SUITE_EXECUTABLE_LOCATION=$(pwd)/test-validator
-          export TEST_DIRECTORY_PATH=$(pwd)/test-temp
-
-          # install the CLFSLoad extension
-          pip3 install clfsload
-
-          keyctl session test python ./testSuite/scripts/run.py
-        name: 'Run_smoke_tests'
-        env:
-          ACCOUNT_NAME: $(ACCOUNT_NAME)
-          ACCOUNT_KEY: $(ACCOUNT_KEY)
-          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
-          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
-          GOOGLE_CLOUD_PROJECT: $(GOOGLE_CLOUD_PROJECT)
-          GOOGLE_APPLICATION_CREDENTIALS: $(ciGCSServiceAccountKey.secureFilePath)
-          ACTIVE_DIRECTORY_APPLICATION_ID: $(ACTIVE_DIRECTORY_APPLICATION_ID)
-          AZCOPY_SPA_CLIENT_SECRET: $(AZCOPY_SPA_CLIENT_SECRET)
-          CONTAINER_OAUTH_URL: $(CONTAINER_OAUTH_URL)
-          CONTAINER_OAUTH_VALIDATE_SAS_URL: $(CONTAINER_OAUTH_VALIDATE_SAS_URL)
-          CONTAINER_SAS_URL: $(CONTAINER_SAS_URL)
-          FILESYSTEM_SAS_URL: $(FILESYSTEM_SAS_URL)
-          FILESYSTEM_URL: $(FILESYSTEM_URL)
-          OAUTH_AAD_ENDPOINT: $(OAUTH_AAD_ENDPOINT)
-          OAUTH_TENANT_ID: $(OAUTH_TENANT_ID)
-          PREMIUM_CONTAINER_SAS_URL: $(PREMIUM_CONTAINER_SAS_URL)
-          S2S_DST_BLOB_ACCOUNT_SAS_URL: $(S2S_DST_BLOB_ACCOUNT_SAS_URL)
-          S2S_SRC_BLOB_ACCOUNT_SAS_URL: $(S2S_SRC_BLOB_ACCOUNT_SAS_URL)
-          S2S_SRC_FILE_ACCOUNT_SAS_URL: $(S2S_SRC_FILE_ACCOUNT_SAS_URL)
-          S2S_SRC_S3_SERVICE_URL: $(S2S_SRC_S3_SERVICE_URL)
-          S2S_SRC_GCP_SERVICE_URL: $(S2S_SRC_GCP_SERVICE_URL)
-          SHARE_SAS_URL: $(SHARE_SAS_URL)
-      - script: |
-          pip install azure-storage-blob==12.0.0b3
-          # the recent release 1.0.0b4 has a breaking change
-          pip install azure-core==1.0.0b3
-          python ./tool_distributed_mutex.py unlock "$(MUTEX_URL)"
-        name: 'Release_the_distributed_mutex'
-        # this runs even if the job was canceled (only if the mutex was acquired by this job)
-        condition: and(always(), eq(variables['isMutexSet'], 'true'))
+#
+#  - job: Build
+#    timeoutInMinutes: 360
+#    strategy:
+#      matrix:
+#        Ubuntu-20:
+#          imageName: 'ubuntu-20.04'
+#          type: 'linux'
+#        MacOS:
+#          imageName: 'macOS-10.15'
+#          type: 'mac-os'
+#    pool:
+#      vmImage: $(imageName)
+#    steps:
+#      - task: GoTool@0
+#        inputs:
+#          version: '1.16'
+#      - script: |
+#          GOARCH=amd64 GOOS=linux go build -o "$(Build.ArtifactStagingDirectory)/azcopy_linux_amd64"
+#          GOARCH=amd64 GOOS=linux go build -tags "se_integration" -o "$(Build.ArtifactStagingDirectory)/azcopy_linux_se_amd64"
+#          GOARCH=arm64 GOOS=linux go build -o "$(Build.ArtifactStagingDirectory)/azcopy_linux_arm64"
+#
+#          GOARCH=amd64 GOOS=windows go build -o "$(Build.ArtifactStagingDirectory)/azcopy_windows_amd64.exe"
+#          GOARCH=386 GOOS=windows go build -o "$(Build.ArtifactStagingDirectory)/azcopy_windows_386.exe"
+#          GOARCH=arm GOARM=7 GOOS=windows go build -o "$(Build.ArtifactStagingDirectory)/azcopy_windows_v7_arm.exe"
+#
+#          cp NOTICE.txt $(Build.ArtifactStagingDirectory)
+#        displayName: 'Generate Linux And Windows Build'
+#        condition: eq(variables.type, 'linux')
+#
+#      - script: |
+#          go build -o "$(Build.ArtifactStagingDirectory)/azcopy_darwin_amd64"
+#        displayName: 'Generate MacOS Build'
+#        condition: eq(variables.type, 'mac-os')
+#
+#      - task: PublishBuildArtifacts@1
+#        displayName: 'Publish Artifacts'
+#        condition: succeededOrFailed()
+#
+#  - job: E2E_Test
+#    timeoutInMinutes: 360
+#    # Creating strategies for GOOS: Windows Server 2019 /macOS X Mojave 10.15/Ubuntu 20.04
+#    strategy:
+#      matrix:
+#        Ubuntu-20:
+#          imageName: 'ubuntu-20.04'
+#          type: 'linux'
+#        Windows:
+#          imageName: 'windows-2019'
+#          type: 'windows'
+#        MacOS:
+#          imageName: 'macOS-10.15'
+#          type: 'mac-os'
+#    pool:
+#      vmImage: $(imageName)
+#
+#    steps:
+#      - task: GoTool@0
+#        inputs:
+#          version: '1.16'
+#
+#      # Running E2E Tests on Linux - AMD64
+#      - script: |
+#          set -e
+#          GOARCH=amd64 GOOS=linux go build -o azcopy_linux_amd64
+#          export AZCOPY_E2E_EXECUTABLE_PATH=$(pwd)/azcopy_linux_amd64
+#          go test -timeout 20m -race -short -cover ./e2etest
+#        env:
+#          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
+#          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
+#          AZCOPY_E2E_ACCOUNT_KEY_HNS: $(AZCOPY_E2E_ACCOUNT_KEY_HNS)
+#          AZCOPY_E2E_ACCOUNT_NAME_HNS: $(AZCOPY_E2E_ACCOUNT_NAME_HNS)
+#          CPK_ENCRYPTION_KEY: $(CPK_ENCRYPTION_KEY)
+#          CPK_ENCRYPTION_KEY_SHA256: $(CPK_ENCRYPTION_KEY_SHA256)
+#        displayName: 'E2E Test Linux - AMD64'
+#        condition: eq(variables.type, 'linux')
+#
+#      # Running E2E Tests on Windows - AMD64
+#      - script: |
+#          go build -o $(System.DefaultWorkingDirectory)/azcopy_windows_amd64.exe
+#          go build -o $(System.DefaultWorkingDirectory)/azcopy_windows_386.exe
+#          echo 'starting E2E tests on windows'
+#          go test -timeout 30m -race -cover -v ./e2etest
+#        env:
+#          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
+#          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
+#          AZCOPY_E2E_ACCOUNT_KEY_HNS: $(AZCOPY_E2E_ACCOUNT_KEY_HNS)
+#          AZCOPY_E2E_ACCOUNT_NAME_HNS: $(AZCOPY_E2E_ACCOUNT_NAME_HNS)
+#          CPK_ENCRYPTION_KEY: $(CPK_ENCRYPTION_KEY)
+#          CPK_ENCRYPTION_KEY_SHA256: $(CPK_ENCRYPTION_KEY_SHA256)
+#          AZCOPY_E2E_EXECUTABLE_PATH: $(System.DefaultWorkingDirectory)/azcopy_windows_amd64.exe
+#        displayName: 'E2E Test Windows - AMD64'
+#        condition: eq(variables.type, 'windows')
+#
+#      # Running E2E Tests on Mac
+#      - script: |
+#          set -e
+#          go build -o azcopy_darwin_amd64
+#          echo 'starting E2E tests on mac-os'
+#          export AZCOPY_E2E_EXECUTABLE_PATH=$(pwd)/azcopy_darwin_amd64
+#          go test -timeout 30m -race -cover -v ./e2etest
+#        env:
+#          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
+#          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
+#          AZCOPY_E2E_ACCOUNT_KEY_HNS: $(AZCOPY_E2E_ACCOUNT_KEY_HNS)
+#          AZCOPY_E2E_ACCOUNT_NAME_HNS: $(AZCOPY_E2E_ACCOUNT_NAME_HNS)
+#          CPK_ENCRYPTION_KEY: $(CPK_ENCRYPTION_KEY)
+#          CPK_ENCRYPTION_KEY_SHA256: $(CPK_ENCRYPTION_KEY_SHA256)
+#        displayName: 'E2E Test MacOs'
+#        condition: eq(variables.type, 'mac-os')
+#
+#  - job: Test_On_Ubuntu
+#    variables:
+#      isMutexSet: 'false'
+#    # allow maximum build time, in case we have build congestion
+#    timeoutInMinutes: 360
+#    pool:
+#      vmImage: 'ubuntu-20.04'
+#    steps:
+#      - task: UsePythonVersion@0
+#        name: 'Set_up_Python'
+#        inputs:
+#          versionSpec: '3.7'
+#      - task: GoTool@0
+#        name: 'Set_up_Golang'
+#        inputs:
+#          version: '1.16'
+#      - task: DownloadSecureFile@1
+#        name: ciGCSServiceAccountKey
+#        displayName: 'Download GCS Service Account Key'
+#        inputs:
+#          secureFile: 'ci-gcs-dev.json'
+#      - script: |
+#          pip install azure-storage-blob==12.0.0b3
+#          # the recent release 1.0.0b4 has a breaking change
+#          pip install azure-core==1.0.0b3
+#          # acquire the mutex before running live tests to avoid conflicts
+#          python ./tool_distributed_mutex.py lock "$(MUTEX_URL)"
+#          # set the variable to indicate that the mutex was actually acquired
+#          echo '##vso[task.setvariable variable=isMutexSet]true'
+#        name: 'Acquire_the_distributed_mutex'
+#      - script: |
+#          # run unit test and build executable
+#          # the set -e line is needed so that the unit tests failure would cause the job to fail properly
+#          # "-check.v" (must be after package list) outputs timings
+#          set -e
+#          go test -timeout 45m -race -short -cover ./cmd ./common ./common/parallel ./ste ./azbfs ./sddl "-check.v"
+#          GOARCH=amd64 GOOS=linux go build -o azcopy_linux_amd64
+#        name: 'Run_unit_tests'
+#        env:
+#          ACCOUNT_NAME: $(ACCOUNT_NAME)
+#          ACCOUNT_KEY: $(ACCOUNT_KEY)
+#          AZCOPY_E2E_ACCOUNT_KEY: $(AZCOPY_E2E_ACCOUNT_KEY)
+#          AZCOPY_E2E_ACCOUNT_NAME: $(AZCOPY_E2E_ACCOUNT_NAME)
+#          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
+#          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
+#          GOOGLE_APPLICATION_CREDENTIALS: $(ciGCSServiceAccountKey.secureFilePath)
+#          GOOGLE_CLOUD_PROJECT: $(GOOGLE_CLOUD_PROJECT)
+#      - script: |
+#          go build -o test-validator ./testSuite/
+#          mkdir test-temp
+#          export AZCOPY_EXECUTABLE_PATH=$(pwd)/azcopy_linux_amd64
+#          export TEST_SUITE_EXECUTABLE_LOCATION=$(pwd)/test-validator
+#          export TEST_DIRECTORY_PATH=$(pwd)/test-temp
+#
+#          # install the CLFSLoad extension
+#          pip3 install clfsload
+#
+#          keyctl session test python ./testSuite/scripts/run.py
+#        name: 'Run_smoke_tests'
+#        env:
+#          ACCOUNT_NAME: $(ACCOUNT_NAME)
+#          ACCOUNT_KEY: $(ACCOUNT_KEY)
+#          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
+#          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
+#          GOOGLE_CLOUD_PROJECT: $(GOOGLE_CLOUD_PROJECT)
+#          GOOGLE_APPLICATION_CREDENTIALS: $(ciGCSServiceAccountKey.secureFilePath)
+#          ACTIVE_DIRECTORY_APPLICATION_ID: $(ACTIVE_DIRECTORY_APPLICATION_ID)
+#          AZCOPY_SPA_CLIENT_SECRET: $(AZCOPY_SPA_CLIENT_SECRET)
+#          CONTAINER_OAUTH_URL: $(CONTAINER_OAUTH_URL)
+#          CONTAINER_OAUTH_VALIDATE_SAS_URL: $(CONTAINER_OAUTH_VALIDATE_SAS_URL)
+#          CONTAINER_SAS_URL: $(CONTAINER_SAS_URL)
+#          FILESYSTEM_SAS_URL: $(FILESYSTEM_SAS_URL)
+#          FILESYSTEM_URL: $(FILESYSTEM_URL)
+#          OAUTH_AAD_ENDPOINT: $(OAUTH_AAD_ENDPOINT)
+#          OAUTH_TENANT_ID: $(OAUTH_TENANT_ID)
+#          PREMIUM_CONTAINER_SAS_URL: $(PREMIUM_CONTAINER_SAS_URL)
+#          S2S_DST_BLOB_ACCOUNT_SAS_URL: $(S2S_DST_BLOB_ACCOUNT_SAS_URL)
+#          S2S_SRC_BLOB_ACCOUNT_SAS_URL: $(S2S_SRC_BLOB_ACCOUNT_SAS_URL)
+#          S2S_SRC_FILE_ACCOUNT_SAS_URL: $(S2S_SRC_FILE_ACCOUNT_SAS_URL)
+#          S2S_SRC_S3_SERVICE_URL: $(S2S_SRC_S3_SERVICE_URL)
+#          S2S_SRC_GCP_SERVICE_URL: $(S2S_SRC_GCP_SERVICE_URL)
+#          SHARE_SAS_URL: $(SHARE_SAS_URL)
+#      - script: |
+#          pip install azure-storage-blob==12.0.0b3
+#          # the recent release 1.0.0b4 has a breaking change
+#          pip install azure-core==1.0.0b3
+#          python ./tool_distributed_mutex.py unlock "$(MUTEX_URL)"
+#        name: 'Release_the_distributed_mutex'
+#        # this runs even if the job was canceled (only if the mutex was acquired by this job)
+#        condition: and(always(), eq(variables['isMutexSet'], 'true'))
