commented some code for testing

diff --git a/build-1es-pipeline.yaml b/build-1es-pipeline.yaml
--- a/build-1es-pipeline.yaml
+++ b/build-1es-pipeline.yaml
@@ -429,125 +429,125 @@ extends:
                   rootFolderOrFile: '$(windows_386)'
                   archiveFile: '$(signed)/azcopy_windows_386_$(azcopy_version).zip'
 
-          - job: Mac
-            timeoutInMinutes: 120
-            pool:
-              name: azcopy-pool
-              image: ubuntu22-1espt
-              os: linux
+          # - job: Mac
+          #   timeoutInMinutes: 120
+          #   pool:
+          #     name: azcopy-pool
+          #     image: ubuntu22-1espt
+          #     os: linux
 
-            templateContext:
-              inputs:
-                - input: pipelineArtifact
-                  artifactName: azcopy-mac-unsigned
-                  targetPath: $(System.DefaultWorkingDirectory)/mac
-                  displayName: 'Download Mac Unsigned'
-                - input: pipelineArtifact
-                  artifactName: azcopy-mac-m1-unsigned
-                  targetPath: $(System.DefaultWorkingDirectory)/mac-m1
-                  displayName: 'Download Mac M1 Unsigned'
-              outputs:
-                - output: pipelineArtifact
-                  targetPath: $(System.DefaultWorkingDirectory)/signed
-                  artifactName: 'azcopy-mac-signed'
-                  displayName: 'Upload Mac Signed'
-                - output: pipelineArtifact
-                  targetPath: $(System.DefaultWorkingDirectory)/binaries
-                  artifactName: 'azcopy-binaries-mac'
-                  displayName: 'Upload Mac Binaries'
+          #   templateContext:
+          #     inputs:
+          #       - input: pipelineArtifact
+          #         artifactName: azcopy-mac-unsigned
+          #         targetPath: $(System.DefaultWorkingDirectory)/mac
+          #         displayName: 'Download Mac Unsigned'
+          #       - input: pipelineArtifact
+          #         artifactName: azcopy-mac-m1-unsigned
+          #         targetPath: $(System.DefaultWorkingDirectory)/mac-m1
+          #         displayName: 'Download Mac M1 Unsigned'
+          #     outputs:
+          #       - output: pipelineArtifact
+          #         targetPath: $(System.DefaultWorkingDirectory)/signed
+          #         artifactName: 'azcopy-mac-signed'
+          #         displayName: 'Upload Mac Signed'
+          #       - output: pipelineArtifact
+          #         targetPath: $(System.DefaultWorkingDirectory)/binaries
+          #         artifactName: 'azcopy-binaries-mac'
+          #         displayName: 'Upload Mac Binaries'
 
-            variables:
-              - group: AZCOPY_SECRET_VAULT
-              - name: mac
-                value: '$(System.DefaultWorkingDirectory)/mac'
-              - name: mac-m1
-                value: '$(System.DefaultWorkingDirectory)/mac-m1'
-              - name: signed
-                value: '$(System.DefaultWorkingDirectory)/signed'
-              - name: binaries
-                value: '$(System.DefaultWorkingDirectory)/binaries'
+          #   variables:
+          #     - group: AZCOPY_SECRET_VAULT
+          #     - name: mac
+          #       value: '$(System.DefaultWorkingDirectory)/mac'
+          #     - name: mac-m1
+          #       value: '$(System.DefaultWorkingDirectory)/mac-m1'
+          #     - name: signed
+          #       value: '$(System.DefaultWorkingDirectory)/signed'
+          #     - name: binaries
+          #       value: '$(System.DefaultWorkingDirectory)/binaries'
 
-            steps:
-              - checkout: none
+          #   steps:
+          #     - checkout: none
 
-              - script: |
-                  sudo apt-get clean
-                  sudo apt-get update
-                  sudo apt-get upgrade -y
-                  sudo apt-get install unzip -y
-                  sudo apt-get install -f --fix-missing
-                  wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
-                  sudo dpkg -i packages-microsoft-prod.deb
-                  sudo apt install apt-transport-https -y
-                  sudo apt install dotnet-sdk-6.0 -y
-                displayName: "Update dependencies"
+          #     - script: |
+          #         sudo apt-get clean
+          #         sudo apt-get update
+          #         sudo apt-get upgrade -y
+          #         sudo apt-get install unzip -y
+          #         sudo apt-get install -f --fix-missing
+          #         wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
+          #         sudo dpkg -i packages-microsoft-prod.deb
+          #         sudo apt install apt-transport-https -y
+          #         sudo apt install dotnet-sdk-6.0 -y
+          #       displayName: "Update dependencies"
 
-              - template: setup/esrp_sign_notarize_macos.yml@self
-                parameters:
-                  FolderPath: $(mac)
-                  ESRP_AZCOPY_MAC_KEY_CODE: $(ESRP_AZCOPY_MAC_KEY_CODE)
-                  Pattern: '*.zip'
+          #     - template: setup/esrp_sign_notarize_macos.yml@self
+          #       parameters:
+          #         FolderPath: $(mac)
+          #         ESRP_AZCOPY_MAC_KEY_CODE: $(ESRP_AZCOPY_MAC_KEY_CODE)
+          #         Pattern: '*.zip'
 
-              - template: setup/esrp_sign_notarize_macos.yml@self
-                parameters:
-                  FolderPath: $(mac-m1)
-                  ESRP_AZCOPY_MAC_KEY_CODE: $(ESRP_AZCOPY_MAC_KEY_CODE)
-                  Pattern: '*.zip'
+          #     - template: setup/esrp_sign_notarize_macos.yml@self
+          #       parameters:
+          #         FolderPath: $(mac-m1)
+          #         ESRP_AZCOPY_MAC_KEY_CODE: $(ESRP_AZCOPY_MAC_KEY_CODE)
+          #         Pattern: '*.zip'
 
-              # Validate signed images have md5sum changed
-              - script: |
-                  mkdir -p $(binaries)
-                  mkdir -p $(signed)
-                  chmod 755 $(mac)/*
-                  rm -rf $(mac)/*.md
-                  chmod 755 $(mac-m1)/*
-                  rm -rf $(mac-m1)/*.md
-                displayName: 'Make Artifacts executable'
+          #     # Validate signed images have md5sum changed
+          #     - script: |
+          #         mkdir -p $(binaries)
+          #         mkdir -p $(signed)
+          #         chmod 755 $(mac)/*
+          #         rm -rf $(mac)/*.md
+          #         chmod 755 $(mac-m1)/*
+          #         rm -rf $(mac-m1)/*.md
+          #       displayName: 'Make Artifacts executable'
 
-              - script: |
-                  mv $(mac)/azcopy* $(signed)/
-                  mv $(mac-m1)/azcopy* $(signed)/
-                displayName: 'Copy required files'
+          #     - script: |
+          #         mv $(mac)/azcopy* $(signed)/
+          #         mv $(mac-m1)/azcopy* $(signed)/
+          #       displayName: 'Copy required files'
 
-              - script: |
-                  mkdir -p unzipped_amd64
-                  unzip -o $(signed)/azcopy*amd64*.zip -d unzipped_amd64
-                  # Use find to retrieve the folder name
-                  amd64FolderName=$(find unzipped_amd64 -maxdepth 1 -type d -name "azcopy_darwin_amd64*")
-                  echo "AMD64 Folder name: $amd64FolderName"
-                  # Check if there is exactly one matching directory for amd64
-                  if [ $(echo "$amd64FolderName" | wc -l) -eq 1 ]; then
-                      echo "Found matching AMD64 directory: $amd64FolderName"
-                      mv $amd64FolderName/azcopy $(binaries)/azcopy_darwin_amd64
-                  else
-                      echo "Error: Expected exactly one matching AMD64 directory, found $(echo "$amd64FolderName" | wc -l)."
-                      exit 1
-                  fi
-                  mkdir -p unzipped_arm64
-                  unzip -o $(signed)/azcopy_darwin_arm64*.zip -d unzipped_arm64
-                  arm64FolderName=$(find unzipped_arm64 -maxdepth 1 -type d -name "azcopy_darwin_arm64*")
-                  echo "ARM64 Folder name: $arm64FolderName"
-                  # Check if there is exactly one matching directory for arm64
-                  if [ $(echo "$arm64FolderName" | wc -l) -eq 1 ]; then
-                      echo "Found matching ARM64 directory: $arm64FolderName"
-                      mv $arm64FolderName/azcopy $(binaries)/azcopy_darwin_arm64
-                  else
-                      echo "Error: Expected exactly one matching ARM64 directory, found $(echo "$arm64FolderName" | wc -l)."
-                      exit 1
-                  fi
-                  mkdir -p unzipped_m1_arm64
-                  unzip -o $(signed)/azcopy_darwin_m1_arm64*.zip -d unzipped_m1_arm64
-                  m1Arm64FolderName=$(find unzipped_m1_arm64 -maxdepth 1 -type d -name "azcopy_darwin_m1_arm64*")
-                  echo "ARM64 M1 Folder name: $m1Arm64FolderName"
-                  # Check if there is exactly one matching directory for arm64
-                  if [ $(echo "$m1Arm64FolderName" | wc -l) -eq 1 ]; then
-                      echo "Found matching ARM64 M1 directory: $m1Arm64FolderName"
-                      mv $m1Arm64FolderName/azcopy $(binaries)/azcopy_darwin_m1_arm64
-                  else
-                      echo "Error: Expected exactly one matching ARM64 M1 directory, found $(echo "$m1Arm64FolderName" | wc -l)."
-                      exit 1
-                  fi
-                displayName:  'Copy signed mac binaries'
+          #     - script: |
+          #         mkdir -p unzipped_amd64
+          #         unzip -o $(signed)/azcopy*amd64*.zip -d unzipped_amd64
+          #         # Use find to retrieve the folder name
+          #         amd64FolderName=$(find unzipped_amd64 -maxdepth 1 -type d -name "azcopy_darwin_amd64*")
+          #         echo "AMD64 Folder name: $amd64FolderName"
+          #         # Check if there is exactly one matching directory for amd64
+          #         if [ $(echo "$amd64FolderName" | wc -l) -eq 1 ]; then
+          #             echo "Found matching AMD64 directory: $amd64FolderName"
+          #             mv $amd64FolderName/azcopy $(binaries)/azcopy_darwin_amd64
+          #         else
+          #             echo "Error: Expected exactly one matching AMD64 directory, found $(echo "$amd64FolderName" | wc -l)."
+          #             exit 1
+          #         fi
+          #         mkdir -p unzipped_arm64
+          #         unzip -o $(signed)/azcopy_darwin_arm64*.zip -d unzipped_arm64
+          #         arm64FolderName=$(find unzipped_arm64 -maxdepth 1 -type d -name "azcopy_darwin_arm64*")
+          #         echo "ARM64 Folder name: $arm64FolderName"
+          #         # Check if there is exactly one matching directory for arm64
+          #         if [ $(echo "$arm64FolderName" | wc -l) -eq 1 ]; then
+          #             echo "Found matching ARM64 directory: $arm64FolderName"
+          #             mv $arm64FolderName/azcopy $(binaries)/azcopy_darwin_arm64
+          #         else
+          #             echo "Error: Expected exactly one matching ARM64 directory, found $(echo "$arm64FolderName" | wc -l)."
+          #             exit 1
+          #         fi
+          #         mkdir -p unzipped_m1_arm64
+          #         unzip -o $(signed)/azcopy_darwin_m1_arm64*.zip -d unzipped_m1_arm64
+          #         m1Arm64FolderName=$(find unzipped_m1_arm64 -maxdepth 1 -type d -name "azcopy_darwin_m1_arm64*")
+          #         echo "ARM64 M1 Folder name: $m1Arm64FolderName"
+          #         # Check if there is exactly one matching directory for arm64
+          #         if [ $(echo "$m1Arm64FolderName" | wc -l) -eq 1 ]; then
+          #             echo "Found matching ARM64 M1 directory: $m1Arm64FolderName"
+          #             mv $m1Arm64FolderName/azcopy $(binaries)/azcopy_darwin_m1_arm64
+          #         else
+          #             echo "Error: Expected exactly one matching ARM64 M1 directory, found $(echo "$m1Arm64FolderName" | wc -l)."
+          #             exit 1
+          #         fi
+          #       displayName:  'Copy signed mac binaries'
       # SignArtifacts end here
 
       - stage: VerifyArtifacts
@@ -638,41 +638,41 @@ extends:
                   azcopy --version
                 displayName: 'Verify rpm'
 
-          - job: MacOS
-            timeoutInMinutes: 120
-            pool:
-              name: Azure Pipelines
-              image: macos-latest
-              os: macOS
-            templateContext:
-              inputs:
-                - input: pipelineArtifact
-                  artifactName: azcopy-mac-signed
-                  targetPath: $(System.DefaultWorkingDirectory)/signed
-                  itemPattern: 'azcopy*amd64*.zip'
-                  displayName: 'Download Mac Signed'
+          # - job: MacOS
+          #   timeoutInMinutes: 120
+          #   pool:
+          #     name: Azure Pipelines
+          #     image: macos-latest
+          #     os: macOS
+          #   templateContext:
+          #     inputs:
+          #       - input: pipelineArtifact
+          #         artifactName: azcopy-mac-signed
+          #         targetPath: $(System.DefaultWorkingDirectory)/signed
+          #         itemPattern: 'azcopy*amd64*.zip'
+          #         displayName: 'Download Mac Signed'
 
-            variables:
-              - name: signed
-                value: '$(System.DefaultWorkingDirectory)/signed'
-              - name: extracted
-                value: '$(System.DefaultWorkingDirectory)/extracted'
+          #   variables:
+          #     - name: signed
+          #       value: '$(System.DefaultWorkingDirectory)/signed'
+          #     - name: extracted
+          #       value: '$(System.DefaultWorkingDirectory)/extracted'
 
-            steps:
-              - checkout: none
+          #   steps:
+          #     - checkout: none
 
-              - script: |
-                  mkdir -p $(extracted)
-                displayName: 'Create extracted path'
+          #     - script: |
+          #         mkdir -p $(extracted)
+          #       displayName: 'Create extracted path'
 
-              - task: ExtractFiles@1
-                inputs:
-                  archiveFilePatterns: '$(signed)/azcopy*amd64*.zip'
-                  destinationFolder: $(extracted)
+          #     - task: ExtractFiles@1
+          #       inputs:
+          #         archiveFilePatterns: '$(signed)/azcopy*amd64*.zip'
+          #         destinationFolder: $(extracted)
 
-              - script: |
-                  $(extracted)/azcopy*amd64*/azcopy --version
-                displayName: 'Verify binary in zip'
+          #     - script: |
+          #         $(extracted)/azcopy*amd64*/azcopy --version
+          #       displayName: 'Verify binary in zip'
 
           - job: Windows_Amd64
             timeoutInMinutes: 120
