change name of stage

diff --git a/build-1es-pipeline.yaml b/build-1es-pipeline.yaml
--- a/build-1es-pipeline.yaml
+++ b/build-1es-pipeline.yaml
@@ -32,51 +32,50 @@ extends:
         image: windows2022-1espt
         os: windows
     stages:
-      - stage: AzCopyVersion
+#      - stage: AzCopyVersion
+#        jobs:
+#          - job: GetAzCopyVersion
+#            pool:
+#              name: azcopy-pool
+#              image: ubuntu22-1espt
+#              os: linux
+#            steps:
+#              - checkout: self
+#                displayName: 'Checkout repository'
+#
+#              - task: GoTool@0
+#                env:
+#                  GO111MODULE: 'on'
+#                inputs:
+#                  version: $(AZCOPY_GOLANG_VERSION)
+#
+#              - script: |
+#                  go build -tags "netgo" -o azcopy
+#                displayName: 'Build AzCopy'
+#
+#              - script: |
+#                  # Run azcopy --version and capture the output
+#                  azcopyOutput=$(./azcopy --version)
+#
+#                  # Extract the version part
+#                  if echo "$azcopyOutput" | grep -q "azcopy version"; then
+#                    version=$(echo "$azcopyOutput" | sed -n 's/^azcopy version \([0-9]*\.[0-9]*\.[0-9]*[^ ]*\).*/\1/p')
+#                    if [[ -n "$version" ]]; then
+#                      echo "Extracted version: $version"
+#                      echo "##vso[task.setvariable variable=azcopy_version;isOutput=true]$version"
+#                    else
+#                      echo "Unable to extract version from azcopy output"
+#                      exit 1
+#                    fi
+#                  else
+#                    echo "azcopy version string not found in output"
+#                    exit 1
+#                  fi
+#                displayName: 'Verify and extract the generated build version'
+#                name: SetAzCopyVersion
+      - stage: UploadToContainer
         jobs:
-          - job: GetAzCopyVersion
-            pool:
-              name: azcopy-pool
-              image: ubuntu22-1espt
-              os: linux
-            steps:
-              - checkout: self
-                displayName: 'Checkout repository'
-
-              - task: GoTool@0
-                env:
-                  GO111MODULE: 'on'
-                inputs:
-                  version: $(AZCOPY_GOLANG_VERSION)
-
-              - script: |
-                  go build -tags "netgo" -o azcopy
-                displayName: 'Build AzCopy'
-
-              - script: |
-                  # Run azcopy --version and capture the output
-                  azcopyOutput=$(./azcopy --version)
-
-                  # Extract the version part
-                  if echo "$azcopyOutput" | grep -q "azcopy version"; then
-                    version=$(echo "$azcopyOutput" | sed -n 's/^azcopy version \([0-9]*\.[0-9]*\.[0-9]*[^ ]*\).*/\1/p')
-                    if [[ -n "$version" ]]; then
-                      echo "Extracted version: $version"
-                      echo "##vso[task.setvariable variable=azcopy_version;isOutput=true]$version"
-                    else
-                      echo "Unable to extract version from azcopy output"
-                      exit 1
-                    fi
-                  else
-                    echo "azcopy version string not found in output"
-                    exit 1
-                  fi
-                displayName: 'Verify and extract the generated build version'
-                name: SetAzCopyVersion
-
-      - stage: ReleaseToContainer
-        jobs:
-          - job: ReleaseToContainer
+          - job: UploadToContainer
             pool:
               name: azcopy-pool
               image: ubuntu22-1espt
@@ -100,7 +99,6 @@ extends:
               - script: |
                   mkdir -p $(release)
                 displayName: 'Test'
-
 #      - stage: BuildArtifacts
 #        dependsOn: AzCopyVersion
 #        jobs:
@@ -894,4 +892,3 @@ extends:
 #                  cd $(extracted)\azcopy*arm64*
 #                  azcopy.exe --version
 #                displayName: 'Verify exe in zip'
-
