commenting as not required for testing

diff --git a/build-1es-pipeline.yaml b/build-1es-pipeline.yaml
--- a/build-1es-pipeline.yaml
+++ b/build-1es-pipeline.yaml
@@ -610,96 +610,96 @@ extends:
             #       artifactName: 'azcopy-binaries-mac'
             #       displayName: 'Upload Mac Binaries'
 
-            variables:
-              - group: AZCOPY_SECRET_VAULT
-              - name: mac
-                value: '$(System.DefaultWorkingDirectory)/mac'
-              - name: mac-m1
-                value: '$(System.DefaultWorkingDirectory)/mac-m1'
-              - name: signed
-                value: '$(System.DefaultWorkingDirectory)/signed'
-              - name: binaries
-                value: '$(System.DefaultWorkingDirectory)/binaries'
+            # variables:
+            #   - group: AZCOPY_SECRET_VAULT
+            #   - name: mac
+            #     value: '$(System.DefaultWorkingDirectory)/mac'
+            #   - name: mac-m1
+            #     value: '$(System.DefaultWorkingDirectory)/mac-m1'
+            #   - name: signed
+            #     value: '$(System.DefaultWorkingDirectory)/signed'
+            #   - name: binaries
+            #     value: '$(System.DefaultWorkingDirectory)/binaries'
 
-            steps:
-              - checkout: none
+            # steps:
+            #   - checkout: none
 
-              - script: |
-                  sudo apt-get update
-                  sudo apt-get install -y unzip
-                displayName: 'Install dependencies'
+            #   - script: |
+            #       sudo apt-get update
+            #       sudo apt-get install -y unzip
+            #     displayName: 'Install dependencies'
 
-              - task: UseDotNet@2
-                inputs:
-                  packageType: 'sdk'
-                  version: '9.0.x'
+            #   - task: UseDotNet@2
+            #     inputs:
+            #       packageType: 'sdk'
+            #       version: '9.0.x'
 
-              - template: setup/esrp_sign_notarize_macos.yml@self
-                parameters:
-                  FolderPath: $(mac)
-                  ESRP_AZCOPY_MAC_KEY_CODE: $(ESRP_AZCOPY_MAC_KEY_CODE)
-                  Pattern: '*.zip'
+            #   - template: setup/esrp_sign_notarize_macos.yml@self
+            #     parameters:
+            #       FolderPath: $(mac)
+            #       ESRP_AZCOPY_MAC_KEY_CODE: $(ESRP_AZCOPY_MAC_KEY_CODE)
+            #       Pattern: '*.zip'
 
-              # - template: setup/esrp_sign_notarize_macos.yml@self
-              #   parameters:
-              #     FolderPath: $(mac-m1)
-              #     ESRP_AZCOPY_MAC_KEY_CODE: $(ESRP_AZCOPY_MAC_KEY_CODE)
-              #     Pattern: '*.zip'
+            #   - template: setup/esrp_sign_notarize_macos.yml@self
+            #     parameters:
+            #       FolderPath: $(mac-m1)
+            #       ESRP_AZCOPY_MAC_KEY_CODE: $(ESRP_AZCOPY_MAC_KEY_CODE)
+            #       Pattern: '*.zip'
 
               # Validate signed images have md5sum changed
-              - script: |
-                  mkdir -p $(binaries)
-                  mkdir -p $(signed)
-                  chmod 755 $(mac)/*
-                  rm -rf $(mac)/*.md
-                  # chmod 755 $(mac-m1)/*
-                  # rm -rf $(mac-m1)/*.md
-                displayName: 'Make Artifacts executable'
+              # - script: |
+              #     mkdir -p $(binaries)
+              #     mkdir -p $(signed)
+              #     chmod 755 $(mac)/*
+              #     rm -rf $(mac)/*.md
+              #     chmod 755 $(mac-m1)/*
+              #     rm -rf $(mac-m1)/*.md
+              #   displayName: 'Make Artifacts executable'
 
-              - script: |
-                  mv $(mac)/azcopy* $(signed)/
-                  # mv $(mac-m1)/azcopy* $(signed)/
-                displayName: 'Copy required files'
+              # - script: |
+              #     mv $(mac)/azcopy* $(signed)/
+              #     mv $(mac-m1)/azcopy* $(signed)/
+              #   displayName: 'Copy required files'
 
-              - script: |
-                  mkdir -p unzipped_amd64
-                  unzip -o $(signed)/azcopy*amd64*.zip -d unzipped_amd64
-                  # Use find to retrieve the folder name
-                  amd64FolderName=$(find unzipped_amd64 -maxdepth 1 -type d -name "azcopy_darwin_amd64*")
-                  echo "AMD64 Folder name: $amd64FolderName"
-                  # Check if there is exactly one matching directory for amd64
-                  if [ $(echo "$amd64FolderName" | wc -l) -eq 1 ]; then
-                      echo "Found matching AMD64 directory: $amd64FolderName"
-                      mv $amd64FolderName/azcopy $(binaries)/azcopy_darwin_amd64
-                  else
-                      echo "Error: Expected exactly one matching AMD64 directory, found $(echo "$amd64FolderName" | wc -l)."
-                      exit 1
-                  fi
-                  mkdir -p unzipped_arm64
-                  unzip -o $(signed)/azcopy_darwin_arm64*.zip -d unzipped_arm64
-                  arm64FolderName=$(find unzipped_arm64 -maxdepth 1 -type d -name "azcopy_darwin_arm64*")
-                  echo "ARM64 Folder name: $arm64FolderName"
-                  # Check if there is exactly one matching directory for arm64
-                  if [ $(echo "$arm64FolderName" | wc -l) -eq 1 ]; then
-                      echo "Found matching ARM64 directory: $arm64FolderName"
-                      mv $arm64FolderName/azcopy $(binaries)/azcopy_darwin_arm64
-                  else
-                      echo "Error: Expected exactly one matching ARM64 directory, found $(echo "$arm64FolderName" | wc -l)."
-                      exit 1
-                  fi
-                  mkdir -p unzipped_m1_arm64
-                  unzip -o $(signed)/azcopy_darwin_m1_arm64*.zip -d unzipped_m1_arm64
-                  m1Arm64FolderName=$(find unzipped_m1_arm64 -maxdepth 1 -type d -name "azcopy_darwin_m1_arm64*")
-                  echo "ARM64 M1 Folder name: $m1Arm64FolderName"
-                  # Check if there is exactly one matching directory for arm64
-                  if [ $(echo "$m1Arm64FolderName" | wc -l) -eq 1 ]; then
-                      echo "Found matching ARM64 M1 directory: $m1Arm64FolderName"
-                      mv $m1Arm64FolderName/azcopy $(binaries)/azcopy_darwin_m1_arm64
-                  else
-                      echo "Error: Expected exactly one matching ARM64 M1 directory, found $(echo "$m1Arm64FolderName" | wc -l)."
-                      exit 1
-                  fi
-                displayName:  'Copy signed mac binaries'
+              # - script: |
+              #     mkdir -p unzipped_amd64
+              #     unzip -o $(signed)/azcopy*amd64*.zip -d unzipped_amd64
+              #     # Use find to retrieve the folder name
+              #     amd64FolderName=$(find unzipped_amd64 -maxdepth 1 -type d -name "azcopy_darwin_amd64*")
+              #     echo "AMD64 Folder name: $amd64FolderName"
+              #     # Check if there is exactly one matching directory for amd64
+              #     if [ $(echo "$amd64FolderName" | wc -l) -eq 1 ]; then
+              #         echo "Found matching AMD64 directory: $amd64FolderName"
+              #         mv $amd64FolderName/azcopy $(binaries)/azcopy_darwin_amd64
+              #     else
+              #         echo "Error: Expected exactly one matching AMD64 directory, found $(echo "$amd64FolderName" | wc -l)."
+              #         exit 1
+              #     fi
+              #     mkdir -p unzipped_arm64
+              #     unzip -o $(signed)/azcopy_darwin_arm64*.zip -d unzipped_arm64
+              #     arm64FolderName=$(find unzipped_arm64 -maxdepth 1 -type d -name "azcopy_darwin_arm64*")
+              #     echo "ARM64 Folder name: $arm64FolderName"
+              #     # Check if there is exactly one matching directory for arm64
+              #     if [ $(echo "$arm64FolderName" | wc -l) -eq 1 ]; then
+              #         echo "Found matching ARM64 directory: $arm64FolderName"
+              #         mv $arm64FolderName/azcopy $(binaries)/azcopy_darwin_arm64
+              #     else
+              #         echo "Error: Expected exactly one matching ARM64 directory, found $(echo "$arm64FolderName" | wc -l)."
+              #         exit 1
+              #     fi
+              #     mkdir -p unzipped_m1_arm64
+              #     unzip -o $(signed)/azcopy_darwin_m1_arm64*.zip -d unzipped_m1_arm64
+              #     m1Arm64FolderName=$(find unzipped_m1_arm64 -maxdepth 1 -type d -name "azcopy_darwin_m1_arm64*")
+              #     echo "ARM64 M1 Folder name: $m1Arm64FolderName"
+              #     # Check if there is exactly one matching directory for arm64
+              #     if [ $(echo "$m1Arm64FolderName" | wc -l) -eq 1 ]; then
+              #         echo "Found matching ARM64 M1 directory: $m1Arm64FolderName"
+              #         mv $m1Arm64FolderName/azcopy $(binaries)/azcopy_darwin_m1_arm64
+              #     else
+              #         echo "Error: Expected exactly one matching ARM64 M1 directory, found $(echo "$m1Arm64FolderName" | wc -l)."
+              #         exit 1
+              #     fi
+              #   displayName:  'Copy signed mac binaries'
         # SignArtifacts ends here
 
       - stage: VerifyArtifacts
