test sign

diff --git a/release-pipelines.yml b/release-pipelines.yml
--- a/release-pipelines.yml
+++ b/release-pipelines.yml
@@ -14,10 +14,10 @@ parameters:
     type: boolean
     default: false
   
-  - name: unit_test
-    displayName: 'Execute Unit Tests'
-    type: boolean
-    default: false
+  # - name: unit_test
+  #   displayName: 'Execute Unit Tests'
+  #   type: boolean
+  #   default: false
 
   - name: post_release
     displayName: 'Post Release on Github'
@@ -1204,7 +1204,7 @@ stages:
         timeoutInMinutes: 120
         strategy:
           matrix:
-            Linux-Signing:
+            Binaries-Signing:
               vmImage: 'Ubuntu-20.04'
               AgentName: "blobfuse-ubuntu20"
         pool:
@@ -1254,7 +1254,7 @@ stages:
           - template: setup/esrp_sign_windows.yml
             parameters:
               FolderPath: '$(Build.ArtifactStagingDirectory)/azCopy-binaries'
-              ESRP_AZCOPY_KEY_CODE: $(ESRP_AZCOPY_KEY_CODE)
+              ESRP_AZCOPY_KEY_CODE: $(ESRP_AZCOPY_WIN_KEY_CODE)
               Pattern: '*.exe'
           
           # Validate signed images have md5sum changed
@@ -1301,18 +1301,12 @@ stages:
             value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
 
         steps:
-          - checkout: none
-
-          #TODO: replace org name from dphulkar-msft to Azure
+          #TODO: remove this after merging to main
           - script: |
-              git clone https://github.com/dphulkar-msft/azure-storage-azcopy
-            displayName: 'Checkout Code'
-            workingDirectory: $(root_dir)
-
-          - script: |
-              git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
-            displayName: 'Checkout Branch'
-            workingDirectory: $(root_dir)/azure-storage-azcopy
+              wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
+              chmod 777 $(work_dir)/go_installer.sh
+              sudo ls -lRt $(work_dir)/
+            displayName: 'list'
 
           # Custom script to install Go-lang
           - task: ShellScript@2
@@ -1372,13 +1366,12 @@ stages:
             value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
 
         steps:
-          - checkout: none
-
-          # TODO: replace org name from dphulkar-msft to Azure
+          #TODO: remove this after merging to main
           - script: |
-              git clone https://github.com/dphulkar-msft/azure-storage-azcopy
-            displayName: 'Checkout Code'
-            workingDirectory: $(root_dir)
+              wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
+              chmod 777 $(work_dir)/go_installer.sh
+              sudo ls -lRt $(work_dir)/
+            displayName: 'list'
       
           - script: |
               git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
@@ -1392,7 +1385,6 @@ stages:
               args: "$(root_dir)/"
             displayName: "GoTool Custom Setup"
 
-          # get glibc version with which build is done
           - script: |
              sudo apt update
              sudo apt --fix-broken install
@@ -1450,18 +1442,17 @@ stages:
             value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
 
         steps:
-          - checkout: none
-
+            #TODO: remove this after merging to main
+          - script: |
+              wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
+              chmod 777 $(work_dir)/go_installer.sh
+              sudo ls -lRt $(work_dir)/
+            displayName: 'list'
+          
           - script: |
               sudo yum update -y
               sudo yum install git -y
             displayName: 'Install Git'
-          
-            #TODO: replace org name from dphulkar-msft to Azure
-          - script: |
-              git clone https://github.com/dphulkar-msft/azure-storage-azcopy
-            displayName: 'Checkout Code'
-            workingDirectory: $(root_dir)
 
           - script: |
               git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
@@ -1533,18 +1524,17 @@ stages:
             value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
 
         steps:
-          - checkout: none
-
           - script: |
               sudo yum update -y
               sudo yum install git -y
             displayName: 'Install Git'
 
-          #TODO: replace org name from dphulkar-msft to Azure
+           #TODO: remove this after merging to main
           - script: |
-              git clone https://github.com/dphulkar-msft/azure-storage-azcopy
-            displayName: 'Checkout Code'
-            workingDirectory: $(root_dir)
+              wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
+              chmod 777 $(work_dir)/go_installer.sh
+              sudo ls -lRt $(work_dir)/
+            displayName: 'list'
 
           - script: |
               git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
@@ -1617,18 +1607,17 @@ stages:
             value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
 
         steps:
-          - checkout: none
-
           - script: |
               sudo tdnf update -y
               sudo tdnf install git -y
             displayName: 'Install Git'
 
-          #TODO: replace org name from dphulkar-msft to Azure
+          #TODO: remove this after merging to main
           - script: |
-              git clone https://github.com/dphulkar-msft/azure-storage-azcopy
-            displayName: 'Checkout Code'
-            workingDirectory: $(root_dir)
+              wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
+              chmod 777 $(work_dir)/go_installer.sh
+              sudo ls -lRt $(work_dir)/
+            displayName: 'list'
 
           - script: |
               git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
@@ -1722,9 +1711,6 @@ stages:
                 eval "$(/opt/homebrew/bin/brew shellenv)"
               fi
 
-              # # Install zip and unzip utilities
-              # brew install zip unzip
-
               # Define variables
               ZIP_FILE_PATH=$(ls $(Build.ArtifactStagingDirectory)/azCopy-mac-signed/azcopy*amd64*.zip)
               EXTRACT_DIR="$(Build.ArtifactStagingDirectory)/extracted"
@@ -1740,83 +1726,83 @@ stages:
 
               # Run the azcopy version command
               ./azcopy_darwin_amd64 --version
-            displayName: 'Install Zip, Extract Files, and Run Version Command on macOS'
+            displayName: 'Install Zip, Extract Files, and Run Version Command'
       
       - job: Set_7
-      #   timeoutInMinutes: 120
-      #   strategy:
-      #     matrix:
-      #       Windows:
-      #         imageName: 'windows-2019'
-      #         type: 'windows'
-      #   pool:
-      #     vmImage: $(imageName)
+        timeoutInMinutes: 120
+        strategy:
+          matrix:
+            Windows:
+              imageName: 'windows-2019'
+              type: 'windows'
+        pool:
+          vmImage: $(imageName)
 
-      #   variables:
-      #     - name: root_dir
-      #       value: '$(System.DefaultWorkingDirectory)'
+        variables:
+          - name: root_dir
+            value: '$(System.DefaultWorkingDirectory)'
           
-      #   steps:
-      #     - task: GoTool@0
-      #       env:
-      #         GO111MODULE: 'on'
-      #       inputs:
-      #         version: $(AZCOPY_GOLANG_VERSION)
+        steps:
+          - task: GoTool@0
+            env:
+              GO111MODULE: 'on'
+            inputs:
+              version: $(AZCOPY_GOLANG_VERSION)
 
-      #     - script: |
-      #         echo 'Running GO Vet'
-      #         go vet 
-      #       displayName: 'Golang Vet - Windows'
-      #       workingDirectory: $(root_dir)
+          - script: |
+              echo 'Running GO Vet'
+              go vet 
+            displayName: 'Golang Vet - Windows'
+            workingDirectory: $(root_dir)
 
-      #     - task: DownloadBuildArtifacts@0
-      #       displayName: 'Download Build Artifacts'
-      #       inputs:
-      #         artifactName: 'azCopy-windows-signed'
-      #         downloadPath: $(Build.ArtifactStagingDirectory)
-      #         itemPattern: azCopy-windows-signed/azcopy*amd64*.zip
+          - task: DownloadBuildArtifacts@0
+            displayName: 'Download Build Artifacts'
+            inputs:
+              artifactName: 'azCopy-windows-signed'
+              downloadPath: $(Build.ArtifactStagingDirectory)
+              itemPattern: azCopy-windows-signed/azcopy*amd64*.zip
           
-      #     - task: PowerShell@2
-      #       inputs:
-      #         targetType: 'inline'
-      #         script: |
-      #           $artifactDir = "$(Build.ArtifactStagingDirectory)\azCopy-windows-signed"
-      #           $extractDir = "$(Build.ArtifactStagingDirectory)\extracted"
+          - task: PowerShell@2
+            inputs:
+              targetType: 'inline'
+              script: |
+                $artifactDir = "$(Build.ArtifactStagingDirectory)\azCopy-windows-signed"
+                $extractDir = "$(Build.ArtifactStagingDirectory)\extracted"
                 
-      #           # Find the zip file matching the pattern
-      #           $zipFile = Get-ChildItem -Path $artifactDir -Filter "azcopy*amd64*.zip" | Select-Object -First 1
+                # Find the zip file matching the pattern
+                $zipFile = Get-ChildItem -Path $artifactDir -Filter "azcopy*amd64*.zip" | Select-Object -First 1
 
-      #           if ($null -eq $zipFile) {
-      #             Write-Error "No zip file found matching pattern 'azcopy*amd64*.zip' in directory: $artifactDir"
-      #             exit 1
-      #           }
+                if ($null -eq $zipFile) {
+                  Write-Error "No zip file found matching pattern 'azcopy*amd64*.zip' in directory: $artifactDir"
+                  exit 1
+                }
 
-      #           $zipFilePath = $zipFile.FullName
+                $zipFilePath = $zipFile.FullName
 
-      #           # Create extraction directory
-      #           New-Item -ItemType Directory -Path $extractDir -Force | Out-Null
+                # Create extraction directory
+                New-Item -ItemType Directory -Path $extractDir -Force | Out-Null
 
-      #           # Extract the zip file
-      #           try {
-      #             Add-Type -AssemblyName System.IO.Compression.FileSystem
-      #             [System.IO.Compression.ZipFile]::ExtractToDirectory($zipFilePath, $extractDir)
-      #           } catch {
-      #             Write-Error "Failed to extract zip file: $_"
-      #             exit 1
-      #           }
+                # Extract the zip file
+                try {
+                  Add-Type -AssemblyName System.IO.Compression.FileSystem
+                  [System.IO.Compression.ZipFile]::ExtractToDirectory($zipFilePath, $extractDir)
+                } catch {
+                  Write-Error "Failed to extract zip file: $_"
+                  exit 1
+                }
 
-      #           # Change to the directory containing azcopy
-      #           Set-Location -Path $extractDir
+                # Change to the directory containing azcopy
+                Set-Location -Path $extractDir
 
-      #           # Verify that azcopy.exe exists
-      #           if (-Not (Test-Path -Path ".\azcopy_windows_amd64\azcopy_windows_amd64.exe")) {
-      #             Write-Error "azcopy.exe not found in extraction directory: $extractDir"
-      #             exit 1
-      #           }
+                # Verify that azcopy.exe exists
+                if (-Not (Test-Path -Path ".\azcopy_windows_amd64\azcopy_windows_amd64.exe")) {
+                  Write-Error "azcopy.exe not found in extraction directory: $extractDir"
+                  exit 1
+                }
 
-      #           # Run the azcopy version command
-      #           .\azcopy_windows_amd64\azcopy_windows_amd64.exe --version
-      #       displayName: 'Extract Files and Run Version Command on Windows'
+                # Run the azcopy version command
+                .\azcopy_windows_amd64\azcopy_windows_amd64.exe --version
+            displayName: 'Extract Files and Run Version Command on Windows'
 
   # TestArtifacts ends here
   
@@ -1839,7 +1825,7 @@ stages:
             value: 'azcopyprivatedrops'
           - name: Release_Account_Name
             value: 'azcopyvnextrelease'
-          - name: test_mode
+          - name: Test_Mode
             value: ${{ parameters.test_mode }}
 
         steps:
@@ -1875,7 +1861,7 @@ stages:
               sudo dpkg --info azcopy-*x86_64.deb
               sudo dpkg -i azcopy-*x86_64.deb
               sudo apt-get install build-essential -y
-            displayName: 'Create drop.zip file and verify azcopy'
+            displayName: 'Create drop.zip file and install azcopy deb package'
             workingDirectory: $(Build.ArtifactStagingDirectory)
 
           - task: ArchiveFiles@2
@@ -1905,7 +1891,7 @@ stages:
                 
                 today=$(date +"%Y%m%d")
                 
-                if [ "${{ parameters.test_mode }}" = "true" ]; then
+                if [ "$(Test_Mode)" = "true" ]; then
                   container_url="https://$(Test_Release_Account_Name).blob.core.windows.net/releases/release-$azcopy_version-$today"
                 else
                   container_url="https://$(Release_Account_Name).blob.core.windows.net/releases/release-$azcopy_version-$today"
