add rhel test

diff --git a/release-pipelines.yml b/release-pipelines.yml
--- a/release-pipelines.yml
+++ b/release-pipelines.yml
@@ -857,234 +857,234 @@ stages:
               artifactName: 'azCopy'
             displayName: 'Publish Artifacts' 
 
-      - job: Set_Rhel_ARM64
-        timeoutInMinutes: 120
-        strategy:
-          matrix:
-            RHEL-9.0:
-              agentName: "blobfuse-rhel9-arm64"
-              vmImage: 'RHEL-9.0'
-              tags: 'tags'
-              container: 'test-cnt-rhel-9-arm64'
+      # - job: Set_Rhel_ARM64
+      #   timeoutInMinutes: 120
+      #   strategy:
+      #     matrix:
+      #       RHEL-9.0:
+      #         agentName: "blobfuse-rhel9-arm64"
+      #         vmImage: 'RHEL-9.0'
+      #         tags: 'tags'
+      #         container: 'test-cnt-rhel-9-arm64'
               
-        pool:
-          name: "blobfuse-ubn-arm64-pool"
-          demands:
-            - ImageOverride -equals $(agentName)
+      #   pool:
+      #     name: "blobfuse-ubn-arm64-pool"
+      #     demands:
+      #       - ImageOverride -equals $(agentName)
 
-        variables:
-          - name: root_dir
-            value: '$(System.DefaultWorkingDirectory)'
-          - name: work_dir
-            value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
+      #   variables:
+      #     - name: root_dir
+      #       value: '$(System.DefaultWorkingDirectory)'
+      #     - name: work_dir
+      #       value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
 
-        steps:
-          - checkout: none
+      #   steps:
+      #     - checkout: none
 
-          - script: |
-              sudo yum update -y
-              sudo yum install git -y
-            displayName: 'Install Git'
+      #     - script: |
+      #         sudo yum update -y
+      #         sudo yum install git -y
+      #       displayName: 'Install Git'
 
-          - script: |
-              git clone https://github.com/Azure/azure-storage-azcopy
-            displayName: 'Checkout Code'
-            workingDirectory: $(root_dir)
+      #     - script: |
+      #         git clone https://github.com/Azure/azure-storage-azcopy
+      #       displayName: 'Checkout Code'
+      #       workingDirectory: $(root_dir)
 
-          - script: |
-              git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
-            displayName: 'Checkout Branch'
-            workingDirectory: $(root_dir)/azure-storage-azcopy
+      #     - script: |
+      #         git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
+      #       displayName: 'Checkout Branch'
+      #       workingDirectory: $(root_dir)/azure-storage-azcopy
 
-          #TODO Removed listing
-          - script: |
-              wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
-              chmod 777 $(work_dir)/go_installer.sh
-              sudo ls -lRt $(work_dir)/
-            displayName: 'listing'
+      #     #TODO Removed listing
+      #     - script: |
+      #         wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
+      #         chmod 777 $(work_dir)/go_installer.sh
+      #         sudo ls -lRt $(work_dir)/
+      #       displayName: 'listing'
           
-          # Custom script to install Go-lang
-          - task: ShellScript@2
-            inputs:
-              scriptPath: "$(work_dir)/go_installer.sh"
-              args: "$(root_dir)/"
-            displayName: "GoTool Custom Setup"
+      #     # Custom script to install Go-lang
+      #     - task: ShellScript@2
+      #       inputs:
+      #         scriptPath: "$(work_dir)/go_installer.sh"
+      #         args: "$(root_dir)/"
+      #       displayName: "GoTool Custom Setup"
 
-          # get glibc version with which build is done
-          - script: |
-             ldd --version
-            displayName: "GLIBC Version"
+      #     # get glibc version with which build is done
+      #     - script: |
+      #        ldd --version
+      #       displayName: "GLIBC Version"
 
-          - task: DownloadBuildArtifacts@0
-            displayName: 'Download Build Artifacts'
-            inputs:
-              artifactName: 'azCopy-signed'
-              downloadPath: $(root_dir)
-              itemPattern: azCopy-signed/azCopy-*$(tags)*arm64.rpm
+      #     - task: DownloadBuildArtifacts@0
+      #       displayName: 'Download Build Artifacts'
+      #       inputs:
+      #         artifactName: 'azCopy-signed'
+      #         downloadPath: $(root_dir)
+      #         itemPattern: azCopy-signed/azCopy-*$(tags)*arm64.rpm
 
-          - script: |
-              ls -l
-              result=$(ls -1 | wc -l)
-              if [ $result -ne 1 ]; then
-                exit 1
-              fi
-            displayName: 'List Downloaded Package'
-            workingDirectory: $(root_dir)/azCopy-signed
+      #     - script: |
+      #         ls -l
+      #         result=$(ls -1 | wc -l)
+      #         if [ $result -ne 1 ]; then
+      #           exit 1
+      #         fi
+      #       displayName: 'List Downloaded Package'
+      #       workingDirectory: $(root_dir)/azCopy-signed
 
-          - script: |
-              for f in ./azcopy*$(tags)*.rpm; do mv -v "$f" "${f/-$(tags)./-$(vmImage).}"; done;
-              cp ./azcopy*$(vmImage)*.rpm $(Build.ArtifactStagingDirectory)
-            displayName: 'Rename Package'
-            workingDirectory: $(root_dir)/azCopy-signed
+      #     - script: |
+      #         for f in ./azcopy*$(tags)*.rpm; do mv -v "$f" "${f/-$(tags)./-$(vmImage).}"; done;
+      #         cp ./azcopy*$(vmImage)*.rpm $(Build.ArtifactStagingDirectory)
+      #       displayName: 'Rename Package'
+      #       workingDirectory: $(root_dir)/azCopy-signed
 
-          - script: |
-              sudo sed -i '/^failovermethod=/d' /etc/yum.repos.d/*.repo
-              sudo rpm -qip azcopy*$(vmImage)*.rpm
-              sudo yum groupinstall "Development Tools" -y              
-              sudo rpm -i azcopy*$(vmImage)*.rpm
-            displayName: 'Install Package'
-            workingDirectory: $(Build.ArtifactStagingDirectory)
+      #     - script: |
+      #         sudo sed -i '/^failovermethod=/d' /etc/yum.repos.d/*.repo
+      #         sudo rpm -qip azcopy*$(vmImage)*.rpm
+      #         sudo yum groupinstall "Development Tools" -y              
+      #         sudo rpm -i azcopy*$(vmImage)*.rpm
+      #       displayName: 'Install Package'
+      #       workingDirectory: $(Build.ArtifactStagingDirectory)
 
-          - script: | 
-              azcopy_linux_arm64 --version
-            displayName: 'Check Version'
+      #     - script: | 
+      #         azcopy_linux_arm64 --version
+      #       displayName: 'Check Version'
 
-          - script: | 
-              azcopy_linux_arm64 --help
-            displayName: 'Check Help'
+      #     - script: | 
+      #         azcopy_linux_arm64 --help
+      #       displayName: 'Check Help'
 
-          # publishing the artifacts generated
-          - task: PublishBuildArtifacts@1
-            inputs:
-              artifactName: 'azcopy'
-            displayName: 'Publish Artifacts'
+      #     # publishing the artifacts generated
+      #     - task: PublishBuildArtifacts@1
+      #       inputs:
+      #         artifactName: 'azcopy'
+      #       displayName: 'Publish Artifacts'
       
-      - job: Set_Rhel_AMD64
-        timeoutInMinutes: 120
-        strategy:
-          matrix:
-            RHEL-7.5:
-              agentName: "blobfuse-rhel7_5"
-              vmImage: 'RHEL-7.5'
-              tags: 'tags'
-              container: 'test-cnt-rhel-75'
-            RHEL-8.6:
-              agentName: "blobfuse-rhel8_6"
-              vmImage: 'RHEL-8.6'
-              container: 'test-cnt-rhel-86'
-            RHEL-9.0:
-              agentName: "blobfuse-rhel9"
-              vmImage: 'RHEL-9.0'
-              tags: 'tags'
-              container: 'test-cnt-rhel-9'
+      # - job: Set_Rhel_AMD64
+      #   timeoutInMinutes: 120
+      #   strategy:
+      #     matrix:
+      #       RHEL-7.5:
+      #         agentName: "blobfuse-rhel7_5"
+      #         vmImage: 'RHEL-7.5'
+      #         tags: 'tags'
+      #         container: 'test-cnt-rhel-75'
+      #       RHEL-8.6:
+      #         agentName: "blobfuse-rhel8_6"
+      #         vmImage: 'RHEL-8.6'
+      #         container: 'test-cnt-rhel-86'
+      #       RHEL-9.0:
+      #         agentName: "blobfuse-rhel9"
+      #         vmImage: 'RHEL-9.0'
+      #         tags: 'tags'
+      #         container: 'test-cnt-rhel-9'
               
-        pool:
-          name: "blobfuse-rhel-pool"
-          demands:
-            - ImageOverride -equals $(agentName)
+      #   pool:
+      #     name: "blobfuse-rhel-pool"
+      #     demands:
+      #       - ImageOverride -equals $(agentName)
 
-        variables:
-          - name: root_dir
-            value: '$(System.DefaultWorkingDirectory)'
-          - name: work_dir
-            value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
+      #   variables:
+      #     - name: root_dir
+      #       value: '$(System.DefaultWorkingDirectory)'
+      #     - name: work_dir
+      #       value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
 
-        steps:
-          - checkout: none
+      #   steps:
+      #     - checkout: none
 
-          - script: |
-              sudo touch /etc/yum.repos.d/centos.repo
-              sudo sh -c 'echo -e "[centos-extras]\nname=Centos extras - $basearch\nbaseurl=http://mirror.centos.org/centos/7/extras/x86_64\nenabled=1\ngpgcheck=1\ngpgkey=http://centos.org/keys/RPM-GPG-KEY-CentOS-7" > /etc/yum.repos.d/centos.repo'
-            condition: or(eq(variables['AgentName'], 'blobfuse-rhel7_5'),eq(variables['AgentName'], 'blobfuse-rhel7_8'))
-            displayName: "Update OS mirrors"
+      #     - script: |
+      #         sudo touch /etc/yum.repos.d/centos.repo
+      #         sudo sh -c 'echo -e "[centos-extras]\nname=Centos extras - $basearch\nbaseurl=http://mirror.centos.org/centos/7/extras/x86_64\nenabled=1\ngpgcheck=1\ngpgkey=http://centos.org/keys/RPM-GPG-KEY-CentOS-7" > /etc/yum.repos.d/centos.repo'
+      #       condition: or(eq(variables['AgentName'], 'blobfuse-rhel7_5'),eq(variables['AgentName'], 'blobfuse-rhel7_8'))
+      #       displayName: "Update OS mirrors"
 
-          - script: |
-              sudo yum update -y
-              sudo yum install git -y
-            displayName: 'Install Git'
+      #     - script: |
+      #         sudo yum update -y
+      #         sudo yum install git -y
+      #       displayName: 'Install Git'
 
-          - script: |
-              git clone https://github.com/Azure/azure-storage-fuse
-            displayName: 'Checkout Code'
-            workingDirectory: $(root_dir)
+      #     - script: |
+      #         git clone https://github.com/Azure/azure-storage-fuse
+      #       displayName: 'Checkout Code'
+      #       workingDirectory: $(root_dir)
 
-          - script: |
-              git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
-            displayName: 'Checkout Branch'
-            workingDirectory: $(root_dir)/azure-storage-azcopy
+      #     - script: |
+      #         git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
+      #       displayName: 'Checkout Branch'
+      #       workingDirectory: $(root_dir)/azure-storage-azcopy
 
-          #TODO Removed listing
-          - script: |
-              wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
-              chmod 777 $(work_dir)/go_installer.sh
-              sudo ls -lRt $(work_dir)/
-            displayName: 'listing'
+      #     #TODO Removed listing
+      #     - script: |
+      #         wget https://raw.githubusercontent.com/dphulkar-msft/azure-storage-azcopy/az-pipelineTest/go_installer.sh -P $(work_dir)/
+      #         chmod 777 $(work_dir)/go_installer.sh
+      #         sudo ls -lRt $(work_dir)/
+      #       displayName: 'listing'
 
-          # Custom script to install Go-lang
-          - task: ShellScript@2
-            inputs:
-              scriptPath: "$(work_dir)/go_installer.sh"
-              args: "$(root_dir)/"
-            displayName: "GoTool Custom Setup"
+      #     # Custom script to install Go-lang
+      #     - task: ShellScript@2
+      #       inputs:
+      #         scriptPath: "$(work_dir)/go_installer.sh"
+      #         args: "$(root_dir)/"
+      #       displayName: "GoTool Custom Setup"
 
-          # get glibc version with which build is done
-          - script: |
-             ldd --version
-            displayName: "GLIBC Version"
+      #     # get glibc version with which build is done
+      #     - script: |
+      #        ldd --version
+      #       displayName: "GLIBC Version"
 
-          - task: DownloadBuildArtifacts@0
-            displayName: 'Download Build Artifacts'
-            inputs:
-              artifactName: 'blobfuse2-signed'
-              downloadPath: $(root_dir)
-              itemPattern: blobfuse2-signed/azcopy*$(tags)*x86_64.rpm
+      #     - task: DownloadBuildArtifacts@0
+      #       displayName: 'Download Build Artifacts'
+      #       inputs:
+      #         artifactName: 'blobfuse2-signed'
+      #         downloadPath: $(root_dir)
+      #         itemPattern: blobfuse2-signed/azcopy*$(tags)*x86_64.rpm
 
-          - script: |
-              ls -l
-              result=$(ls -1 | wc -l)
-              if [ $result -ne 1 ]; then
-                exit 1
-              fi
-            displayName: 'List Downloaded Package'
-            workingDirectory: $(root_dir)/azCopy-signed
+      #     - script: |
+      #         ls -l
+      #         result=$(ls -1 | wc -l)
+      #         if [ $result -ne 1 ]; then
+      #           exit 1
+      #         fi
+      #       displayName: 'List Downloaded Package'
+      #       workingDirectory: $(root_dir)/azCopy-signed
 
-          - script: |
-              for f in ./azcopy*$(tags)*.rpm; do mv -v "$f" "${f/-$(tags)./-$(vmImage).}"; done;
-              cp ./azcopy*$(vmImage)*.rpm $(Build.ArtifactStagingDirectory)
-              if [ $(agentName) == "blobfuse-rhel7_5" ]; then
-                f=`ls ./blobfuse2*$(vmImage)*.rpm`
-                cp "$f" $(sed 's:RHEL-7.5:RHEL-7.8:' <<< "$f")
-                cp "$f" $(sed 's:RHEL-7.5:RHEL-8.1:' <<< "$f")
-                cp "$f" $(sed 's:RHEL-7.5:RHEL-8.2:' <<< "$f")
-                cp ./azcopy*RHEL-7.8*.rpm $(Build.ArtifactStagingDirectory)
-                cp ./azcopy*RHEL-8*.rpm $(Build.ArtifactStagingDirectory)
-                rm -rf ./azcopy*RHEL-7.8*.rpm
-                rm -rf ./azcopy*RHEL-8*.rpm
-              fi
-            displayName: 'Rename Package'
-            workingDirectory: $(root_dir)/azCopy-signed
+      #     - script: |
+      #         for f in ./azcopy*$(tags)*.rpm; do mv -v "$f" "${f/-$(tags)./-$(vmImage).}"; done;
+      #         cp ./azcopy*$(vmImage)*.rpm $(Build.ArtifactStagingDirectory)
+      #         if [ $(agentName) == "blobfuse-rhel7_5" ]; then
+      #           f=`ls ./blobfuse2*$(vmImage)*.rpm`
+      #           cp "$f" $(sed 's:RHEL-7.5:RHEL-7.8:' <<< "$f")
+      #           cp "$f" $(sed 's:RHEL-7.5:RHEL-8.1:' <<< "$f")
+      #           cp "$f" $(sed 's:RHEL-7.5:RHEL-8.2:' <<< "$f")
+      #           cp ./azcopy*RHEL-7.8*.rpm $(Build.ArtifactStagingDirectory)
+      #           cp ./azcopy*RHEL-8*.rpm $(Build.ArtifactStagingDirectory)
+      #           rm -rf ./azcopy*RHEL-7.8*.rpm
+      #           rm -rf ./azcopy*RHEL-8*.rpm
+      #         fi
+      #       displayName: 'Rename Package'
+      #       workingDirectory: $(root_dir)/azCopy-signed
 
-          - script: |
-              sudo sed -i '/^failovermethod=/d' /etc/yum.repos.d/*.repo
-              sudo rpm -qip azcopy*$(vmImage)*.rpm
-              sudo yum groupinstall "Development Tools" -y
-              sudo rpm -i azcopy*$(vmImage)*.rpm
-            displayName: 'Install Package'
-            workingDirectory: $(Build.ArtifactStagingDirectory)
+      #     - script: |
+      #         sudo sed -i '/^failovermethod=/d' /etc/yum.repos.d/*.repo
+      #         sudo rpm -qip azcopy*$(vmImage)*.rpm
+      #         sudo yum groupinstall "Development Tools" -y
+      #         sudo rpm -i azcopy*$(vmImage)*.rpm
+      #       displayName: 'Install Package'
+      #       workingDirectory: $(Build.ArtifactStagingDirectory)
 
-          - script: | 
-              azcopy_linux_amd64 --version
-            displayName: 'Check Version'
+      #     - script: | 
+      #         azcopy_linux_amd64 --version
+      #       displayName: 'Check Version'
 
-          - script: | 
-              azcopy_linux_amd64 --help
-            displayName: 'Check Help'
+      #     - script: | 
+      #         azcopy_linux_amd64 --help
+      #       displayName: 'Check Help'
 
-          # publishing the artifacts generated
-          - task: PublishBuildArtifacts@1
-            inputs:
-              artifactName: 'azcopy'
-            displayName: 'Publish Artifacts'
+      #     # publishing the artifacts generated
+      #     - task: PublishBuildArtifacts@1
+      #       inputs:
+      #         artifactName: 'azcopy'
+      #       displayName: 'Publish Artifacts'
 
       # - job: Set_3
       #   timeoutInMinutes: 120
