Add msi to signing step

diff --git a/release-pipeline.yml b/release-pipeline.yml
--- a/release-pipeline.yml
+++ b/release-pipeline.yml
@@ -42,6 +42,11 @@ parameters:
     type: boolean
     default: false
 
+  - name: publish_docker_image
+    displayName: 'Build and Push Docker Image'
+    type: boolean
+    default: false
+
 # Do not trigger this pipeline automatically
 trigger: none
 pr: none
@@ -813,7 +818,7 @@ stages:
             parameters:
               FolderPath: $(Build.ArtifactStagingDirectory)/azCopy-windows-temp
               ESRP_AZCOPY_WIN_KEY_CODE: $(ESRP_AZCOPY_WIN_KEY_CODE)
-              Pattern: 'azcopy_windows*, *.msi'
+              Pattern: '*.exe;*.msi'
 
           - script: |
               rm -rf azCopy-windows-temp/*.md
@@ -1085,15 +1090,8 @@ stages:
         steps:
           - checkout: none
 
-          - script: |
-              sudo apt update
-              sudo apt --fix-broken install
-              ldd --version
-            displayName: "GLIBC Version"
-
           - template: setup/test_artifacts.yml
             parameters:
-              go_version: '$(AZCOPY_GOLANG_VERSION)'
               artifact_name: 'azCopy-binaries'
               download_path: '$(System.DefaultWorkingDirectory)'
               item_pattern: 'azCopy-binaries/azcopy_linux*amd64'
@@ -1138,15 +1136,9 @@ stages:
           vmImage: $(vmImage)
         steps:
           - checkout: none
-          - script: |
-              sudo apt update
-              sudo apt --fix-broken install
-              ldd --version
-            displayName: "GLIBC Version"
 
           - template: setup/test_artifacts.yml
             parameters:
-              go_version: '$(AZCOPY_GOLANG_VERSION)'
               artifact_name: 'azCopy-linux-signed'
               download_path: '$(System.DefaultWorkingDirectory)'
               item_pattern: 'azCopy-linux-signed/azcopy_linux_*amd64*.tar.gz'
@@ -1229,17 +1221,16 @@ stages:
             - ImageOverride -equals $(AgentName)
         steps:
           - checkout: none
-          
+
           - script: |
               sudo apt update
               sudo apt-get install libsecret-1-dev -y
               sudo apt --fix-broken install
               ldd --version
-            displayName: "GLIBC Version"
+            displayName: "Libsecret Install"
   
           - template: setup/test_artifacts.yml
             parameters:
-              go_version: '$(AZCOPY_GOLANG_VERSION)'
               artifact_name: 'azCopy-linux-signed'
               download_path: '$(System.DefaultWorkingDirectory)'
               item_pattern: 'azCopy-linux-signed/azcopy_linux_*arm64*.tar.gz'
@@ -1329,13 +1320,12 @@ stages:
           - script: |
               sudo apt update
               sudo apt-get install libsecret-1-dev -y
-              sudo apt --fix-broken install -y
+              sudo apt --fix-broken install
               ldd --version
-            displayName: "GLIBC Version"
+            displayName: "Libsecret Install"
 
           - template: setup/test_artifacts.yml
             parameters:
-              go_version: '$(AZCOPY_GOLANG_VERSION)'
               artifact_name: 'azCopy-binaries'
               download_path: '$(System.DefaultWorkingDirectory)'
               item_pattern: 'azCopy-binaries/azcopy_linux*arm64'
@@ -1384,19 +1374,8 @@ stages:
         steps:
           - checkout: none
 
-          - script: |
-              sudo yum update -y
-              sudo yum install git -y
-            displayName: 'Install Git'
-
-          # get glibc version with which build is done
-          - script: |
-             ldd --version
-            displayName: "GLIBC Version"
-
           - template: setup/test_artifacts.yml
             parameters:
-              go_version: '$(AZCOPY_GOLANG_VERSION)'
               artifact_name: 'azCopy-linux-signed'
               download_path: '$(System.DefaultWorkingDirectory)'
               item_pattern: 'azCopy-linux-signed/azcopy-*arm64.rpm'
@@ -1431,22 +1410,11 @@ stages:
         steps:
           - checkout: none
 
-          - script: |
-              sudo yum update -y
-              sudo yum install git -y
-            displayName: 'Install Git'
-
           - template: setup/test_artifacts.yml
             parameters:
-              go_version: '$(AZCOPY_GOLANG_VERSION)'
               artifact_name: 'azCopy-linux-signed'
               download_path: '$(System.DefaultWorkingDirectory)'
               item_pattern: 'azCopy-linux-signed/azcopy-*x86_64.rpm'
-          
-          # get glibc version with which build is done
-          - script: |
-             ldd --version
-            displayName: "GLIBC Version"
 
           - script: |
               sudo sed -i '/^failovermethod=/d' /etc/yum.repos.d/*.repo
@@ -1478,23 +1446,12 @@ stages:
 
         steps:
           - checkout: none
-          
-          - script: |
-              sudo tdnf update -y
-              sudo tdnf install git -y
-            displayName: 'Install dependencies'
       
           - template: setup/test_artifacts.yml
             parameters:
-              go_version: '$(AZCOPY_GOLANG_VERSION)'
               artifact_name: 'azCopy-linux-signed'
               download_path: '$(System.DefaultWorkingDirectory)'
               item_pattern: 'azCopy-linux-signed/mariner/azcopy-*x86_64.rpm'
-
-          # get glibc version with which build is done
-          - script: |
-             ldd --version
-            displayName: "GLIBC Version"             
 
           - script: |
               sudo rpm -qip azcopy*x86_64.rpm
@@ -1524,18 +1481,6 @@ stages:
             value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
 
         steps:
-          - task: GoTool@0
-            env:
-              GO111MODULE: 'on'
-            inputs:
-              version: $(AZCOPY_GOLANG_VERSION)
-
-          - script: |
-              echo 'Running GO Vet'
-              go vet 
-            displayName: 'Golang Vet - Mac'
-            workingDirectory: $(System.DefaultWorkingDirectory)
-
           - task: DownloadBuildArtifacts@0
             displayName: 'Download Build Artifacts'
             inputs:
@@ -1593,18 +1538,6 @@ stages:
             value: '$(System.DefaultWorkingDirectory)'
           
         steps:
-          - task: GoTool@0
-            env:
-              GO111MODULE: 'on'
-            inputs:
-              version: $(AZCOPY_GOLANG_VERSION)
-
-          - script: |
-              echo 'Running GO Vet'
-              go vet 
-            displayName: 'Golang Vet - Windows'
-            workingDirectory: $(root_dir)
-
           - task: DownloadBuildArtifacts@0
             displayName: 'Download Build Artifacts'
             inputs:
@@ -1698,12 +1631,6 @@ stages:
         steps:
           - checkout: none
 
-          - script: |
-              sudo apt update
-              sudo apt --fix-broken install
-              ldd --version
-            displayName: "GLIBC Version"
-
           - task: DownloadBuildArtifacts@0
             displayName: 'Download Build Artifacts'
             inputs:
@@ -1739,18 +1666,6 @@ stages:
             value: '$(System.DefaultWorkingDirectory)'
           
         steps:
-          - task: GoTool@0
-            env:
-              GO111MODULE: 'on'
-            inputs:
-              version: $(AZCOPY_GOLANG_VERSION)
-
-          - script: |
-              echo 'Running GO Vet'
-              go vet 
-            displayName: 'Golang Vet - Windows'
-            workingDirectory: $(root_dir)
-
           - task: DownloadBuildArtifacts@0
             displayName: 'Download Build Artifacts'
             inputs:
@@ -1931,9 +1846,9 @@ stages:
                 today=$(date +"%Y%m%d")
                 
                 if [ $(Publish_To_Container) = "True" ]; then
-                  container_url="https://$(Release_Account_Name).blob.core.windows.net/releases/release-$azcopy_version-$today"
+                  container_url="https://$(Release_Account_Name).blob.core.windows.net/%24web/releases/release-$azcopy_version-$today"
                 else
-                  container_url="https://$(Test_Release_Account_Name).blob.core.windows.net/releases/release-$azcopy_version-$today"
+                  container_url="https://$(Test_Release_Account_Name).blob.core.windows.net/%24web/releases/release-$azcopy_version-$today"
                 fi
                 echo "Artifacts will be uploaded to: $container_url"
                 
@@ -1946,9 +1861,107 @@ stages:
                 AZCOPY_AUTO_LOGIN_TYPE=AzCLI $executable_name cp "$(Build.ArtifactStagingDirectory)/*.zip" "$container_url" --put-md5=true
 
                 if [ $(Publish_To_M1_Container) = "True" ]; then
-                  m1_container_url="https://azcopyvnextrelease.blob.core.windows.net/azcopy-m1-drops/azcopy-$azcopy_version-$today"
+                  m1_container_url="https://$(Release_Account_Name).blob.core.windows.net/%24web/azcopy-m1-drops/azcopy-$azcopy_version-$today"
                   AZCOPY_AUTO_LOGIN_TYPE=AzCLI $executable_name cp "$(Build.ArtifactStagingDirectory)/azCopy-binaries/azcopy_darwin_m1_arm64" "$m1_container_url" --put-md5=true
                 fi
+
+  - ${{ if eq(parameters.publish_docker_image, true) }}:
+    - stage: BuildAndPublishDockerImage
+      dependsOn: TestArtifacts
+      condition: succeeded('TestArtifacts')
+      jobs:
+        - job: Set_1_Ubuntu_Mariner_AMD64
+          strategy:
+            matrix:
+              Ubuntu_amd64:
+                agentName: "blobfuse-ubuntu22"
+                vmImage: 'Ubuntu-22.04'
+                container: 'test-cnt-ubn-22'
+          pool:
+            vmImage: $(vmImage)
+
+          variables:
+          - group: AZCOPY_SECRET_VAULT
+          - name: root_dir
+            value: '$(System.DefaultWorkingDirectory)'
+          - name: work_dir
+            value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
+
+          steps:
+            - checkout: none
+            - script: |
+                git clone https://github.com/Azure/azure-storage-azcopy
+              displayName: 'Checkout Code'
+              workingDirectory: $(root_dir)
+
+            - script: |
+                git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
+              displayName: 'Checkout branch'
+              workingDirectory: $(work_dir)
+
+            - script: |
+                chmod 777 *.sh
+                ./dockerinstall.sh
+
+                ./buildcontainer.sh Dockerfile ubuntu-x86_64
+                ./publishcontainer.sh $(AZCOPY_DOCKER_REG_USER)  $(AZCOPY_DOCKER_REG_PWD) ubuntu-x86_64
+
+                ./buildcontainer.sh DockerfileMariner mariner-x86_64
+                ./publishcontainer.sh $(AZCOPY_DOCKER_REG_USER)  $(AZCOPY_DOCKER_REG_PWD) mariner-x86_64
+
+              displayName: "Create docker image and push to the containers registry"
+              workingDirectory: $(work_dir)/docker
+
+        - job: Set_2_Ubuntu_ARM64
+          timeoutInMinutes: 120
+          strategy:
+            matrix:
+              Ubuntu-22-ARM64:
+                vmImage: 'Ubuntu-22.04'
+                container: 'test-cnt-ubn-22-arm64'
+                AgentName: "blobfuse-ubn22-arm64"
+          pool:
+            name: "blobfuse-ubn-arm64-pool"
+            demands:
+              - ImageOverride -equals $(AgentName)
+
+          variables:
+          - group: AZCOPY_SECRET_VAULT
+          - name: root_dir
+            value: '$(System.DefaultWorkingDirectory)'
+          - name: work_dir
+            value: '$(System.DefaultWorkingDirectory)/azure-storage-azcopy'
+
+          steps:
+            - checkout: none
+            - script: |
+                git clone https://github.com/Azure/azure-storage-azcopy
+              displayName: 'Checkout Code'
+              workingDirectory: $(root_dir)
+
+            - script: |
+                git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`
+              displayName: 'Checkout branch'
+              workingDirectory: $(work_dir)
+
+            - task: ShellScript@2
+              inputs:
+                scriptPath: "$(work_dir)/go_installer.sh"
+                args: "$(root_dir)/ $(AZCOPY_GOLANG_VERSION)"
+              displayName: "Installing Go tools"
+
+            - script: |
+                sudo apt update
+                sudo apt --fix-broken install
+              displayName: "Install dependencies"
+
+            - script: |
+                chmod 777 *.sh
+                ./dockerinstall.sh
+                ./buildcontainer.sh DockerfileArm64 ubuntu-arm64
+                ./publishcontainer.sh $(AZCOPY_DOCKER_REG_USER)  $(AZCOPY_DOCKER_REG_PWD) ubuntu-arm64
+              displayName: "Create docker image for arm64 and push to the containers registry"
+              workingDirectory: $(work_dir)/docker
 
   - ${{ if eq(parameters.post_release, true) }}:
     - stage: ReleaseToGithub
@@ -2154,14 +2167,31 @@ stages:
             - group: AZCOPY_TESTS_VAR
             - name: root_dir
               value: '$(System.DefaultWorkingDirectory)'
+            - name: Release_Account_Name
+              value: 'azcopyvnextrelease'
+          
+          steps:
+            - checkout: none
+
+            - script: |
+                sudo apt-get install python3 -y
+                python3 --version
+              displayName: 'Installing Python'
+
+            - task: DownloadBuildArtifacts@0
+              displayName: 'Download Build Artifacts'
+              inputs:
+                artifactName: 'azCopy-linux-signed'
+                downloadPath: $(Build.ArtifactStagingDirectory)
+            
             # install azcopy
             - script: |
                 rm -rf /usr/local/bin/azcopy
                 rm -rf /usr/bin/azcopy
                 cd $(Build.ArtifactStagingDirectory)/azCopy-linux-signed
-                ls azcopy*.arm64.deb
-                sudo dpkg --info azcopy-*arm64.deb
-                sudo dpkg -i azcopy-*arm64.deb
+                ls azcopy*.x86_64.deb
+                sudo dpkg --info azcopy-*x86_64.deb
+                sudo dpkg -i azcopy-*x86_64.deb
                 azcopy --version
               displayName: 'Installing azcopy'
             
@@ -2171,8 +2201,30 @@ stages:
               displayName: 'Getting Python script'
               workingDirectory: $(root_dir)
 
-            - script: |
-                pip install azure-storage-blob
-                python3 releaseVersionUpdate.py "$(VERSION_CNT_SAS_URL)" "`azcopy --version`"
-              displayName: 'Updating version number'
-              workingDirectory: $(root_dir)
+            - task: AzureCLI@2
+              displayName: 'Updating version number with Azure CLI'
+              inputs:
+                azureSubscription: 'ESRP KeyVault identity'
+                scriptType: bash
+                scriptLocation: inlineScript
+                inlineScript: |
+                  export AZCOPY_AUTO_LOGIN_TYPE=AzCLI
+                  
+                  #Extract the version number 
+                  azcopy_version=$(azcopy --version | awk '{print $3}' | head -n 1)
+                  echo "azcopy version: $azcopy_version"
+                  
+                  #Upload to release version blob file
+                  upload_url="https://$(Release_Account_Name).blob.core.windows.net/%24web/releasemetadata/latest_version.txt"
+                  echo "$azcopy_version" | azcopy copy "$upload_url" --from-to=PipeBlob --log-level=DEBUG --output-type=text > azcopy_output.txt
+                  
+                  # Handle errors 
+                  if [ $? -eq 0 ]; then
+                    echo "Release version file successfully uploaded." 
+                  else
+                    echo "File failed to upload: " 
+                    cat azcopy_output.txt
+                    exit 1
+                  fi
+                workingDirectory: $(root_dir)
+                displayName: "Updating version number"
