add msi based login

diff --git a/azurePipelineTemplates/run_scenarios.yml b/azurePipelineTemplates/run_scenarios.yml
--- a/azurePipelineTemplates/run_scenarios.yml
+++ b/azurePipelineTemplates/run_scenarios.yml
@@ -21,85 +21,190 @@ parameters:
     type: string
 
 steps:
-  - task: AzureCLI@2
+  - task: PowerShell@2
+        inputs: 
+          targetType: 'inline'
+          script: 'Install-Module -Name Az.Accounts -Scope CurrentUser -Repository PSGallery -AllowClobber -Force'
+          pwsh: 'true'
+        displayName: 'Install Powershell Az Module'
+
+      - task: GoTool@0
+        inputs:
+          version: $(AZCOPY_GOLANG_VERSION_COVERAGE)
+
+      - bash: |
+          npm install -g azurite
+          mkdir azurite
+          azurite --silent --location azurite --debug azurite\debug.log &
+        displayName: 'Install and Run Azurite'
+
+   # Install azcli
+  - script: |
+      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+      az --version
+    displayName: 'Install Azure CLI'
+
+  # azcli login
+  - script: |
+      az login --identity --username $(AZCOPY_MSI_APP_ID)
+    displayName: 'Azure CLI login'
+
+  - script: |
+      # Print "Building executable"
+      echo "Building executable"
+      
+      # Set environment variables
+      $build_name = '${{ parameters.build_name }}'
+      $env:GOOS = '${{ parameters.goos }}'
+      $env:GOARCH = '${{ parameters.goarch }}'
+      $env:AZCOPY_AUTO_LOGIN_TYPE="MSI"
+      $env:CGO_ENABLED = '${{ parameters.cgo_enabled }}'
+
+      go build -cover -o $build_name
+
+      # Check if the executable was created
+      if (-Not (Test-Path "./$build_name")) {
+          Write-Error "Executable not found: $build_name"
+          exit 1
+      }
+      Write-Output "Executable built successfully: $build_name"
+
+      ######################################################## Scenario 1 ########################################################
+
+      # Right now we dont have this fix available in the older version of AzCopy. So, we are using the latest version of AzCopy to run the scenarios.
+      # We will update this workaround once the fix is available in the older version of AzCopy.
+
+      echo "Scenario 1: Test successful copying from BlobToPipe"
+
+      echo "Creating container '${{ parameters.container_name }}' in storage account '${{ parameters.storage_account_name }}'"
+      & "./$build_name" "make" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}"
+
+      echo "Copy a test file from local to the created container"
+      echo "Hello, Azure!" > myfile.txt
+      & "./$build_name" "cp" "myfile.txt" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}"
+
+      & "./$build_name" "cp" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}/myfile.txt" "--from-to=BlobPipe" "--check-md5" "FailIfDifferentOrMissing" > filename
+      
+      if ($LASTEXITCODE -eq 0) {
+          Write-Output "Successfully executed the scenario."
+      } else {
+          Write-Error "AzCopy command failed with exit code $LASTEXITCODE."
+      }
+
+      # Perform cleanup
+      echo "Perform cleanup"
+      echo "Remove the test file from the container"
+      & "./$build_name" "rm" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}/myfile.txt"
+      echo "Remove the container from the storage account"
+      & az storage container delete --name ${{ parameters.container_name }} --account-name ${{ parameters.storage_account_name }}
+
+      ######################################################## Scenario 2 ########################################################
+
+      # Test copying from Object Replication Policy source container to destination container
+      # Assign an object replication policy to a storage account. 
+      # Perform azcopy copy operation to copy the blob to another container.
+
+      echo "Scenario 2: Test copying from Object Replication Policy source container to destination container"
+
+      echo "Creating a test file named 'myfile.txt' and copying it to the source container '${{ parameters.orp_source_container_name }}' within the storage account '${{ parameters.orp_source_account_name }}', which has the ORP policy applied."
+      echo "Hello, Azure!" > myfile.txt
+      & "./$build_name" "cp" "myfile.txt" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{ parameters.orp_source_container_name }}"
+
+      echo "Copy the test file from the source container to the destination container '${{ parameters.destination_container_name }}' in storage account '${{ parameters.orp_destination_account_name }}'."
+      & "./$build_name" "cp" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{parameters.orp_source_container_name}}" "https://${{ parameters.orp_destination_account_name }}.blob.core.windows.net/${{parameters.destination_container_name}}" --recursive
+
+      if ($LASTEXITCODE -eq 0) {
+          Write-Output "Successfully executed the scenario."
+      } else {
+          Write-Error "AzCopy command failed with exit code $LASTEXITCODE."
+      }
+
+      # Perform cleanup
+      echo "Perform cleanup"
+      echo "Remove the test file from the source and destination container"
+      & "./$build_name" "rm" "https://${{ parameters.orp_destination_account_name }}.blob.core.windows.net/${{parameters.destination_container_name}}/myfile.txt"
+      & "./$build_name" "rm" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{ parameters.orp_source_container_name }}/myfile.txt"
     displayName: "Run Scenarios"
-    inputs:
-      azureSubscription: azcopyTestScenarios
-      addSpnToEnvironment: true
-      scriptType: pscore
-      scriptLocation: inlineScript
-      inlineScript: |
-        # Print "Building executable"
-        Write-Output "Building executable"
+
+  # - task: AzureCLI@2
+  #   displayName: "Run Scenarios"
+  #   inputs:
+  #     azureSubscription: azcopyTestScenarios
+  #     addSpnToEnvironment: true
+  #     scriptType: pscore
+  #     scriptLocation: inlineScript
+  #     inlineScript: |
+  #       # Print "Building executable"
+  #       Write-Output "Building executable"
         
-        # Set environment variables
-        $build_name = '${{ parameters.build_name }}'
-        $env:GOOS = '${{ parameters.goos }}'
-        $env:GOARCH = '${{ parameters.goarch }}'
-        $env:AZCOPY_AUTO_LOGIN_TYPE="AzCLI"
-        $env:CGO_ENABLED = '${{ parameters.cgo_enabled }}'
+  #       # Set environment variables
+  #       $build_name = '${{ parameters.build_name }}'
+  #       $env:GOOS = '${{ parameters.goos }}'
+  #       $env:GOARCH = '${{ parameters.goarch }}'
+  #       $env:AZCOPY_AUTO_LOGIN_TYPE="MSI"
+  #       $env:CGO_ENABLED = '${{ parameters.cgo_enabled }}'
 
-        go build -cover -o $build_name
+  #       go build -cover -o $build_name
 
-        # Check if the executable was created
-        if (-Not (Test-Path "./$build_name")) {
-            Write-Error "Executable not found: $build_name"
-            exit 1
-        }
-        Write-Output "Executable built successfully: $build_name"
+  #       # Check if the executable was created
+  #       if (-Not (Test-Path "./$build_name")) {
+  #           Write-Error "Executable not found: $build_name"
+  #           exit 1
+  #       }
+  #       Write-Output "Executable built successfully: $build_name"
 
-        ######################################################## Scenario 1 ########################################################
+  #       ######################################################## Scenario 1 ########################################################
 
-        # Right now we dont have this fix available in the older version of AzCopy. So, we are using the latest version of AzCopy to run the scenarios.
-        # We will update this workaround once the fix is available in the older version of AzCopy.
+  #       # Right now we dont have this fix available in the older version of AzCopy. So, we are using the latest version of AzCopy to run the scenarios.
+  #       # We will update this workaround once the fix is available in the older version of AzCopy.
 
-        echo "Scenario 1: Test successful copying from BlobToPipe"
+  #       echo "Scenario 1: Test successful copying from BlobToPipe"
 
-        echo "Creating container '${{ parameters.container_name }}' in storage account '${{ parameters.storage_account_name }}'"
-        & "./$build_name" "make" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}"
+  #       echo "Creating container '${{ parameters.container_name }}' in storage account '${{ parameters.storage_account_name }}'"
+  #       & "./$build_name" "make" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}"
 
-        echo "Copy a test file from local to the created container"
-        echo "Hello, Azure!" > myfile.txt
-        & "./$build_name" "cp" "myfile.txt" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}"
+  #       echo "Copy a test file from local to the created container"
+  #       echo "Hello, Azure!" > myfile.txt
+  #       & "./$build_name" "cp" "myfile.txt" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}"
 
-        & "./$build_name" "cp" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}/myfile.txt" "--from-to=BlobPipe" "--check-md5" "FailIfDifferentOrMissing" > filename
+  #       & "./$build_name" "cp" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}/myfile.txt" "--from-to=BlobPipe" "--check-md5" "FailIfDifferentOrMissing" > filename
         
-        if ($LASTEXITCODE -eq 0) {
-            Write-Output "Successfully executed the scenario."
-        } else {
-            Write-Error "AzCopy command failed with exit code $LASTEXITCODE."
-        }
+  #       if ($LASTEXITCODE -eq 0) {
+  #           Write-Output "Successfully executed the scenario."
+  #       } else {
+  #           Write-Error "AzCopy command failed with exit code $LASTEXITCODE."
+  #       }
 
-        # Perform cleanup
-        echo "Perform cleanup"
-        echo "Remove the test file from the container"
-        & "./$build_name" "rm" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}/myfile.txt"
-        echo "Remove the container from the storage account"
-        & az storage container delete --name ${{ parameters.container_name }} --account-name ${{ parameters.storage_account_name }}
+  #       # Perform cleanup
+  #       echo "Perform cleanup"
+  #       echo "Remove the test file from the container"
+  #       & "./$build_name" "rm" "https://${{ parameters.storage_account_name }}.blob.core.windows.net/${{ parameters.container_name }}/myfile.txt"
+  #       echo "Remove the container from the storage account"
+  #       & az storage container delete --name ${{ parameters.container_name }} --account-name ${{ parameters.storage_account_name }}
 
-        ######################################################## Scenario 2 ########################################################
+  #       ######################################################## Scenario 2 ########################################################
 
-        # Test copying from Object Replication Policy source container to destination container
-        # Assign an object replication policy to a storage account. 
-        # Perform azcopy copy operation to copy the blob to another container.
+  #       # Test copying from Object Replication Policy source container to destination container
+  #       # Assign an object replication policy to a storage account. 
+  #       # Perform azcopy copy operation to copy the blob to another container.
 
-        echo "Scenario 2: Test copying from Object Replication Policy source container to destination container"
+  #       echo "Scenario 2: Test copying from Object Replication Policy source container to destination container"
 
-        echo "Creating a test file named 'myfile.txt' and copying it to the source container '${{ parameters.orp_source_container_name }}' within the storage account '${{ parameters.orp_source_account_name }}', which has the ORP policy applied."
-        echo "Hello, Azure!" > myfile.txt
-        & "./$build_name" "cp" "myfile.txt" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{ parameters.orp_source_container_name }}"
+  #       echo "Creating a test file named 'myfile.txt' and copying it to the source container '${{ parameters.orp_source_container_name }}' within the storage account '${{ parameters.orp_source_account_name }}', which has the ORP policy applied."
+  #       echo "Hello, Azure!" > myfile.txt
+  #       & "./$build_name" "cp" "myfile.txt" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{ parameters.orp_source_container_name }}"
 
-        echo "Copy the test file from the source container to the destination container '${{ parameters.destination_container_name }}' in storage account '${{ parameters.orp_destination_account_name }}'."
-        & "./$build_name" "cp" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{parameters.orp_source_container_name}}" "https://${{ parameters.orp_destination_account_name }}.blob.core.windows.net/${{parameters.destination_container_name}}" --recursive
+  #       echo "Copy the test file from the source container to the destination container '${{ parameters.destination_container_name }}' in storage account '${{ parameters.orp_destination_account_name }}'."
+  #       & "./$build_name" "cp" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{parameters.orp_source_container_name}}" "https://${{ parameters.orp_destination_account_name }}.blob.core.windows.net/${{parameters.destination_container_name}}" --recursive
 
-        if ($LASTEXITCODE -eq 0) {
-            Write-Output "Successfully executed the scenario."
-        } else {
-            Write-Error "AzCopy command failed with exit code $LASTEXITCODE."
-        }
+  #       if ($LASTEXITCODE -eq 0) {
+  #           Write-Output "Successfully executed the scenario."
+  #       } else {
+  #           Write-Error "AzCopy command failed with exit code $LASTEXITCODE."
+  #       }
 
-        # Perform cleanup
-        echo "Perform cleanup"
-        echo "Remove the test file from the source and destination container"
-        & "./$build_name" "rm" "https://${{ parameters.orp_destination_account_name }}.blob.core.windows.net/${{parameters.destination_container_name}}/myfile.txt"
-        & "./$build_name" "rm" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{ parameters.orp_source_container_name }}/myfile.txt"
+  #       # Perform cleanup
+  #       echo "Perform cleanup"
+  #       echo "Remove the test file from the source and destination container"
+  #       & "./$build_name" "rm" "https://${{ parameters.orp_destination_account_name }}.blob.core.windows.net/${{parameters.destination_container_name}}/myfile.txt"
+  #       & "./$build_name" "rm" "https://${{ parameters.orp_source_account_name }}.blob.core.windows.net/${{ parameters.orp_source_container_name }}/myfile.txt"
